---
title: "Macroparasite Model - Berding 1987"
author: "Brendan Haile"
date: "8/1/2022"
output: word_document
---

```{r Packages}
library(deSolve)
library(tidyverse)
library(cowplot)
```

```{r Function - Exponential Growth}
#Creating the function
macroParasite <- function(t, x, parameters){
  H <- x[1]
  P <- x[2]
  with(                                   
       as.list(params),                   
       {                                  
         dH <- (b-d)*H-alpha*P
         dP <- (beta*H*lambda*P)/(gamma+beta*H) - P*(d+mu+alpha) - (P*P*alpha*(k+1))/(k*H)
         dXlist <- c(dH,dP)                
         list(dXlist)                         
       }
       )
}
```

```{r Function - Logistic Growth}
#Recreating the macroparasite function but with logistic growth

# list of parameters for quick reference
# b = per capita host birth rate
# d = per capita host mortality
# alpha = additional per capita host mortality due to parasite burden (P/H)*H
# beta = transmission (ingestion) rate of parasites by host
# lambda = external parasite production rate (per parasite)
# gamma = per capita loss rate of entl parasite stages
# mu = parasite mortality within hosts
# k = overdispersion parameter; measures parasite Dispersion (low k = highly aggregated in few hosts, high k = equally distributed among hosts)

macroParasiteLogistic <- function(t, x, parameters){
  H <- x[1]
  P <- x[2]
  with(                                   
       as.list(params),                   
       {                                  
         dH <- (b-d)*H*(1-H/KcarryCap)-alpha*P
         dP <- (beta*H*lambda*P)/(gamma+beta*H) - P*(d+mu+alpha) - (P*P*alpha*(k+1))/(k*H)
         dXlist <- c(dH,dP)                
         list(dXlist)                         
       }
       )
}
```

```{r Parameters}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014
b <- 0.56                  #8^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.56
d <- 0.14                  #2^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.14
alpha <- 0.0035          #5*10^-4 (daily rate) multiplied by 7 to get weekly rate of 0.000154 [this has a range going down to 2.2^10-5 (daily) or 0.000154 weekly rate] ~~~WE USE LOWER BOUND HERE BECAUSE THAT WAS LOW PROTEIN DIET~~~    
beta <- 0.0105             #1.5^10^-3 (daily rate) multiplied by 7 to get weekly rate of 0.0105 [this has a range going up to 6*10^-3 (daily) or 0.042 weekly rate]
KcarryCap <- 120            #40 taken from Forbes2014 Figure 1 (40 voles/0.0625hectare)      [taking 3 quadrats]    
lambda <- 1260             #180 (daily rate) multiplied by 7 to get weekly rate of 1260
gamma <- 1820              #260 (daily rate) multiplied by 7 to get weekly rate of 1820 [old value from Fenton2007 is 0.5]
mu <- 0.0392               #5.6^10^-3 (daily rate) multiplied by 7 to get weekly rate ~~~ONLY NATURAL DEATH OF PARASITE NO HOST IMMUNE RESPONSE~~~
k <- 1.31                  #range of 1.31 to 5.44
```
```{r Parameter Colors for Graphing}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014
b <- "#1F78B4"
d <- "#FB9A99"
alpha <- "#A6CEE3"    
betaClust <-"#B2DF8A"
betaSpread <- "#33A02C"
KcarryCap <- "#FDBF6F" 
lambda <- "#6A3D9A"
gamma <- "#E31A1C"
mu <- "#000000"
kClust <- "#FF7F00"
kSpread <- "#CAB2D6"

```

```{r Impact of Resources - Spread & Clustered}
#Clustered
    #b (per capita host birth rate) INCREASES with resources
    #d (per capita host mortality) DECREASES with resources
    #alpha (additional per capita host mortality due to parasite burden) DECREASES with resources
    #beta (transmission/ingestion rate of parasites by host) INCREASES with resources
        #rodents gather at food site increasing exposure
    #lambda (external parasite production rate (per parasite)) INCREASES with resources
    #gamma (per capita loss rate of environmental parasite stages) NO CHANGE with resources
    #mu (parasite mortality within hosts) INCREASES with resources
    #k (overdispersion parameter) INCREASES with resources
        #rodents gather at food site increasing host availability for macroparasites which may even out spread
    #KcarryCap INCREASES with resources

#Spread
    #b (per capita host birth rate) INCREASES with resources
    #d (per capita host mortality) DECREASES with resources
    #alpha (additional per capita host mortality due to parasite burden) DECREASES with resources
    #beta (transmission/ingestion rate of parasites by host) DECREASES with resources
        #rodents remain spread out due to widespread resource availability which limits contact with macroparasites
            #possible not effected? less overlap and contact so might decrease. unsure
    #lambda (external parasite production rate (per parasite)) INCREASES with resources
    #gamma (per capita loss rate of environmental parasite stages) NO CHANGE by resources
    #mu (parasite mortality within hosts) INCREASES with resources
    #k (overdispersion parameter) DECREASES with resources
        #rodents spend less time traveling and foraging decreasing host availability for macroparasites which may lead to superhosts. Revisits by same rodent host might be infected by later generations of macroparasites.
    #KcarryCap INCREASES with resources

#Differences in Clustered vs Spread
  #beta (transmission/ingestion rate of parasites by host)
  #k (overdispersion parameter)

```
```{r Formula - Impact of Resources is Proportional}
#Resources vary from 1-3 in increments of 0.2
resource <- seq(1, 3, by=0.2)
  #resource = 1 is the baseline natural resource availability
  #resource = 1.2 is a 20% increase in resources (supplementation)
  #resource = 2.0 is a 100% increase in resources
  #resource = 2.4 is a 140% increase in resources

b0 <- 0.56                  #8^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.56
d0 <- 0.14                  #2^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.14
alpha0 <- 0.0035          #5*10^-4 (daily rate) multiplied by 7 to get weekly rate of 0.000154 [this has a range going down to 2.2^10-5 (daily) or 0.000154 weekly rate] ~~~WE USE LOWER BOUND HERE BECAUSE THAT WAS LOW PROTEIN DIET~~~    
beta0 <- 0.0105             #1.5^10^-3 (daily rate) multiplied by 7 to get weekly rate of 0.0105 [this has a range going up to 6*10^-3 (daily) or 0.042 weekly rate]
KcarryCap0 <- 120            #40 taken from Forbes2014 Figure 1 (40 voles/0.0625hectare)      [taking 3 quadrats]    
lambda0 <- 1260             #180 (daily rate) multiplied by 7 to get weekly rate 
gamma0 <- 1820               #260 (daily rate) multiplied by 7 to get weekly rate of 1820 [old value from Fenton2007 is 0.5]
mu0 <- 0.0392               #5.6^10^-3 (daily rate) multiplied by 7 to get weekly rate
k0 <- 1.31                  #range of 1.31 to 5.44

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
betarClust = beta0*resource
betarSpread = beta0/resource
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
mur = mu0*resource
krClust = k0*resource
krSpread = k0/resource
```

```{r - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
resource <- seq(1, 2, by=0.05)

xstart <- c(H=119, P=1)
seasons <- (26*2)+1 #One season is 26 weeks. So we use (26*x)+1 because we start a 1
time <- seq(1,seasons,by=1)

#Parameter Values
b0 <- 0.56                  #8^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.56
d0 <- 0.14                  #2^10^-2 (daily rate) multiplied by 7 to get weekly rate of 0.14
alpha0 <- 0.0035          #5*10^-4 (daily rate) multiplied by 7 to get weekly rate of 0.0035 [this has a range going down to 2.2^10-5 (daily) or 0.000154 weekly rate] ~~~WE USE LOWER BOUND HERE BECAUSE THAT WAS LOW PROTEIN DIET~~~    
beta0 <- 0.0105             #1.5^10^-3 (daily rate) multiplied by 7 to get weekly rate of 0.0105 [this has a range going up to 6*10^-3 (daily) or 0.042 weekly rate]
KcarryCap0 <- 120            #40 taken from Forbes2014 Figure 1 (40 voles/0.0625hectare)      [taking 3 quadrats]    
lambda0 <- 1260             #180 (daily rate) multiplied by 7 to get weekly rate 
gamma0 <- 1820               #260 (daily rate) multiplied by 7 to get weekly rate of 1820 [old value from Fenton2007 is 0.5]
mu0 <- 0.0392               #5.6^10^-3 (daily rate) multiplied by 7 to get weekly rate ~~~ONLY NATURAL DEATH OF PARASITE NO HOST IMMUNE RESPONSE~~~
k0 <- 1.31                  #range of 1.31 to 5.44

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
betarPositive = beta0*resource
betarNegative = beta0/resource
betarNull = beta0+(resource*0)
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
murPositive = mu0*resource
krPositive = k0*resource
krNegative = k0/resource
krNull = k0+(resource*0)

```

```{r Model - Berding 1987 + Forbes 2014 - Logistic Growth - Short - Host Immune System Wins 6 panel (alpha and mu_pos)}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=119, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positiveered effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k & b) 
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

#################################################################################################################################################################
  
  #Null effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positiveered effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k & muPositive) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}


hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostPointsAlpha <- gather(hostEquilibriumAlpha, key="Parameter_Descriptions", value="Host_Population", -R)
hostsAlpha <- ggplot(data=hostPointsAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

parasitePointsAlpha <- gather(parasiteEquilibriumAlpha, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesAlpha <- ggplot(data=parasitePointsAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsAlpha <- gather(pphEquilibriumAlpha, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphAlpha <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("52 Weeks") + 
  theme_bw()

hostPointsMuPositive <- gather(hostEquilibriumMuPositive, key="Parameter_Descriptions", value="Host_Population", -R)
hostsMuPositive <- ggplot(data=hostPointsMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

parasitePointsMuPositive <- gather(parasiteEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesMuPositive <- ggplot(data=parasitePointsMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsMuPositive <- gather(pphEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphMuPositive <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("52 Weeks") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsAlpha, pphAlpha, parasitesAlpha, hostsMuPositive, pphMuPositive, parasitesMuPositive, labels=NULL, ncol=3, nrow=2)
```

```{r Model - Berding 1987 + Forbes 2014 - Logistic Growth - Short Negative vs Null vs Positive (beta, k, alpha)}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=119, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k & alpha)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positive effect of Resources (beta & k & alpha)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k & alpha) 
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

}

hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostPointsAlpha <- gather(hostEquilibriumAlpha, key="Parameter_Descriptions", value="Host_Population", -R)
hostsAlpha <- ggplot(data=hostPointsAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

parasitePointsAlpha <- gather(parasiteEquilibriumAlpha, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesAlpha <- ggplot(data=parasitePointsAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle("26 Weeks") + 
  theme_bw()

pphPointsAlpha <- gather(pphEquilibriumAlpha, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphAlpha <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle(" ") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsAlpha, parasitesAlpha, pphAlpha, legendPlot, labels=NULL, nrow=1)
```
```{r Model - Berding 1987 + Forbes 2014 - Logistic Growth - Short Negative vs Null vs Positive (beta, k, mu_pos)}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014

#Creating empty vectors
equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()


for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=119, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positiveered effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k & muPositive) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )


#Graphing
hostPointsMuPositive <- gather(hostEquilibriumMuPositive, key="Parameter_Descriptions", value="Host_Population", -R)
hostsMuPositive <- ggplot(data=hostPointsMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

parasitePointsMuPositive <- gather(parasiteEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesMuPositive <- ggplot(data=parasitePointsMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsMuPositive <- gather(pphEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphMuPositive <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("52 Weeks") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsMuPositive, pphMuPositive, parasitesMuPositive, legendPlot, labels=NULL, nrow=1)
```

```{r - Finding Minimum and Maximum Values for each combination}
#Hosts
hostMinAlphaNeg <- (min(hostEquilibriumAlpha$H_NegativeAlpha)-hostEquilibriumAlpha$H_NegativeAlpha[1])/hostEquilibriumAlpha$H_NegativeAlpha[1]*100
hostMaxAlphaNeg <- (max(hostEquilibriumAlpha$H_NegativeAlpha)-hostEquilibriumAlpha$H_NegativeAlpha[1])/hostEquilibriumAlpha$H_NegativeAlpha[1]*100

hostMinAlphaNull <- (min(hostEquilibriumAlpha$H_NullAlpha)-hostEquilibriumAlpha$H_NullAlpha[1])/hostEquilibriumAlpha$H_NullAlpha[1]*100
hostMaxAlphaNull <- (max(hostEquilibriumAlpha$H_NullAlpha)-hostEquilibriumAlpha$H_NullAlpha[1])/hostEquilibriumAlpha$H_NullAlpha[1]*100

hostMinAlphaPos <- (min(hostEquilibriumAlpha$H_PositiveAlpha)-hostEquilibriumAlpha$H_PositiveAlpha[1])/hostEquilibriumAlpha$H_PositiveAlpha[1]*100
hostMaxAlphaPos <- (max(hostEquilibriumAlpha$H_PositiveAlpha)-hostEquilibriumAlpha$H_PositiveAlpha[1])/hostEquilibriumAlpha$H_PositiveAlpha[1]*100

hostMinMuNeg <- (min(hostEquilibriumMuPositive$H_NegativeMu)-hostEquilibriumMuPositive$H_NegativeMu[1])/hostEquilibriumMuPositive$H_NegativeMu[1]*100
hostMaxMuNeg <- (max(hostEquilibriumMuPositive$H_NegativeMu)-hostEquilibriumMuPositive$H_NegativeMu[1])/hostEquilibriumMuPositive$H_NegativeMu[1]*100

hostMinMuNull <- (min(hostEquilibriumMuPositive$H_NullMu)-hostEquilibriumMuPositive$H_NullMu[1])/hostEquilibriumMuPositive$H_NullMu[1]*100
hostMaxMuNull <- (max(hostEquilibriumMuPositive$H_NullMu)-hostEquilibriumMuPositive$H_NullMu[1])/hostEquilibriumMuPositive$H_NullMu[1]*100

hostMinMuPos <- (min(hostEquilibriumMuPositive$H_PositiveMu)-hostEquilibriumMuPositive$H_PositiveMu[1])/hostEquilibriumMuPositive$H_PositiveMu[1]*100
hostMaxMuPos <- (max(hostEquilibriumMuPositive$H_PositiveMu)-hostEquilibriumMuPositive$H_PositiveMu[1])/hostEquilibriumMuPositive$H_PositiveMu[1]*100

######################################################################################################

#PpH
pphMinAlphaNeg <- (min(pphEquilibriumAlpha$PpH_NegativeAlpha)-pphEquilibriumAlpha$PpH_NegativeAlpha[1])/pphEquilibriumAlpha$PpH_NegativeAlpha[1]*100
pphMaxAlphaNeg <- (max(pphEquilibriumAlpha$PpH_NegativeAlpha)-pphEquilibriumAlpha$PpH_NegativeAlpha[1])/pphEquilibriumAlpha$PpH_NegativeAlpha[1]*100

pphMinAlphaNull <- (min(pphEquilibriumAlpha$PpH_NullAlpha)-pphEquilibriumAlpha$PpH_NullAlpha[1])/pphEquilibriumAlpha$PpH_NullAlpha[1]*100
pphMaxAlphaNull <- (max(pphEquilibriumAlpha$PpH_NullAlpha)-pphEquilibriumAlpha$PpH_NullAlpha[1])/pphEquilibriumAlpha$PpH_NullAlpha[1]*100

pphMinAlphaPos <- (min(pphEquilibriumAlpha$PpH_PositiveAlpha)-pphEquilibriumAlpha$PpH_PositiveAlpha[1])/pphEquilibriumAlpha$PpH_PositiveAlpha[1]*100
pphMaxAlphaPos <- (max(pphEquilibriumAlpha$PpH_PositiveAlpha)-pphEquilibriumAlpha$PpH_PositiveAlpha[1])/pphEquilibriumAlpha$PpH_PositiveAlpha[1]*100

pphMinMuNeg <- (min(pphEquilibriumMuPositive$PpH_NegativeMu)-pphEquilibriumMuPositive$PpH_NegativeMu[1])/pphEquilibriumMuPositive$PpH_NegativeMu[1]*100
pphMaxMuNeg <- (max(pphEquilibriumMuPositive$PpH_NegativeMu)-pphEquilibriumMuPositive$PpH_NegativeMu[1])/pphEquilibriumMuPositive$PpH_NegativeMu[1]*100

pphMinMuNull <- (min(pphEquilibriumMuPositive$PpH_NullMu)-pphEquilibriumMuPositive$PpH_NullMu[1])/pphEquilibriumMuPositive$PpH_NullMu[1]*100
pphMaxMuNull <- (max(pphEquilibriumMuPositive$PpH_NullMu)-pphEquilibriumMuPositive$PpH_NullMu[1])/pphEquilibriumMuPositive$PpH_NullMu[1]*100

pphMinMuPos <- (min(pphEquilibriumMuPositive$PpH_PositiveMu)-pphEquilibriumMuPositive$PpH_PositiveMu[1])/pphEquilibriumMuPositive$PpH_PositiveMu[1]*100
pphMaxMuPos <- (max(pphEquilibriumMuPositive$PpH_PositiveMu)-pphEquilibriumMuPositive$PpH_PositiveMu[1])/pphEquilibriumMuPositive$PpH_PositiveMu[1]*100

######################################################################################################

#Parasites
parasiteMinAlphaNeg <- min(parasiteEquilibriumAlpha$P_NegativeAlpha)
parasiteMaxAlphaNeg <- max(parasiteEquilibriumAlpha$P_NegativeAlpha)

parasiteMinAlphaNull <- min(parasiteEquilibriumAlpha$P_NullAlpha)
parasiteMaxAlphaNull <- max(parasiteEquilibriumAlpha$P_NullAlpha)

parasiteMinAlphaPos <- min(parasiteEquilibriumAlpha$P_PositiveAlpha)
parasiteMaxAlphaPos <- max(parasiteEquilibriumAlpha$P_PositiveAlpha)

parasiteMinMuNeg <- min(parasiteEquilibriumMuPositive$P_NegativeMu)
parasiteMaxMuNeg <- max(parasiteEquilibriumMuPositive$P_NegativeMu)

parasiteMinMuNull <- min(parasiteEquilibriumMuPositive$P_NullMu)
parasiteMaxMuNull <- max(parasiteEquilibriumMuPositive$P_NullMu)

parasiteMinMuPos <- min(parasiteEquilibriumMuPositive$P_PositiveMu)
parasiteMaxMuPos <- max(parasiteEquilibriumMuPositive$P_PositiveMu)

```

```{r - Global Maximum for Parasites per Host - Positive + Alpha}
hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

hosts <- ggplot(data=hostEquilibriumAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  #geom_line(aes(y=H_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=H_NullAlpha), color="green", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=H_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") +
  theme_bw()

parasites <- ggplot(data=parasiteEquilibriumAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  #geom_line(aes(y=P_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=P_NullAlpha), color="green", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=P_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pph <- ggplot(data=pphEquilibriumAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +  
  #geom_line(aes(y=PpH_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=PpH_NullAlpha), color="green", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=PpH_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host"))) +
  ggtitle("52 Weeks") + 
  theme_bw()

plot_grid(hosts, pph, parasites, labels=NULL, ncol=3, nrow=1)
```
```{r - Global Minimum for Parasites AND Parasites per Host - Negative + MuPos}
hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )


legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

hosts <- ggplot(data=hostEquilibriumMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 130, by=20)) +
  expand_limits(y=c(30,130)) +
  geom_line(aes(y=H_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=H_NullMu), color="green", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=H_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") +
  theme_bw()

parasites <- ggplot(data=parasiteEquilibriumMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  expand_limits(y=c(0,7000)) +
  geom_line(aes(y=P_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=P_NullMu), color="green", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=P_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pph <- ggplot(data=pphEquilibriumMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(0, 180, by=20)) +
  expand_limits(y=c(0,180)) +
  geom_line(aes(y=PpH_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=PpH_NullMu), color="green", show.legend = FALSE, size = 1.2) +
  #geom_line(aes(y=PpH_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host"))) +
  ggtitle("52 Weeks") + 
  theme_bw()

plot_grid(hosts, pph, parasites, labels=NULL, ncol=3, nrow=1)
```

```{r - TEST DETER - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
resource <- seq(1, 2, by=0.05)

xstart <- c(H=69, P=1)
seasons <- (26*10) #One season is 26 weeks. So we use (26*x)+1 because we start a 1
time <- seq(1,seasons,by=1)

#Parameter Values - Many are Monthly rates so we can convert those to Weekly Rates by multiplying with 12/52
b0 <- 0.138               #monthly rate = 0.5980 then weekly rate = 0.5980*12/52 = 0.138
d0 <- 0.0462              #monthly rate = 1/5 then weekly rate = 1/5*12/52 = 0.0462
alpha0 <- 1.92*10^(-4)    #monthly rate = 8.33*10^(-4) then weekly rate = 8.33*10^(-4)*12/52 = 1.92*10^(-4)
beta0 <- 1.2*10^(-8)      #monthly rate = 5.2*10^(-8) then weekly rate = 5.2*10^(-8)*12/52 = 1.2*10^(-8)
KcarryCap0 <- 70         #value = 70 per Hectare (100x100m grid)
lambda0 <- 20769          #monthly rate = 90000 [This seems ridiculously high] then weekly rate = 90000*12/52 = 20769
gamma0 <- 0.0769          #monthly rate = 1/3 then weekly rate = 1/3*12/52 = 0.0769
mu0 <- 0.0865             #monthly rate = 0.375 then weekly rate = 0.375*12/52 = 0.0865
k0 <- 1                   #value = 1

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
betarPositive = beta0*resource
betarNegative = beta0/resource
betarNull = beta0+(resource*0)
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
murPositive = mu0*resource
murNegative = mu0/resource
krPositive = k0*resource
krNegative = k0/resource
krNull = k0+(resource*0)
```

```{r Model - Test DETER - Logistic Growth - Short - Host Immune System Wins 6 panel (alpha and mu_pos)}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=69, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positiveered effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k & b) 
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

#################################################################################################################################################################
  
  #Null effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positiveered effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k & muPositive) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}


hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostPointsAlpha <- gather(hostEquilibriumAlpha, key="Parameter_Descriptions", value="Host_Population", -R)
hostsAlpha <- ggplot(data=hostPointsAlpha, aes(x=R)) +
  #scale_y_continuous(breaks=seq(30, 130, by=20)) +
  #expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

parasitePointsAlpha <- gather(parasiteEquilibriumAlpha, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesAlpha <- ggplot(data=parasitePointsAlpha, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsAlpha <- gather(pphEquilibriumAlpha, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphAlpha <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 180, by=20)) +
  #expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("260 Weeks (10 Seasons)") + 
  theme_bw()

hostPointsMuPositive <- gather(hostEquilibriumMuPositive, key="Parameter_Descriptions", value="Host_Population", -R)
hostsMuPositive <- ggplot(data=hostPointsMuPositive, aes(x=R)) +
  #scale_y_continuous(breaks=seq(30, 130, by=20)) +
  #expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

parasitePointsMuPositive <- gather(parasiteEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesMuPositive <- ggplot(data=parasitePointsMuPositive, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsMuPositive <- gather(pphEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphMuPositive <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 180, by=20)) +
  #expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("260 Weeks (10 Seasons)") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsAlpha, pphAlpha, parasitesAlpha, hostsMuPositive, pphMuPositive, parasitesMuPositive, labels=NULL, ncol=3, nrow=2)
```

```{r - TEST DETER MONTHLY - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
resource <- seq(1, 2, by=0.05)

xstart <- c(H=69, P=1)
monthsBreeding <- (12*5) #One year is 12 months
time <- seq(1,monthsBreeding,by=1)

#Parameter Values - Many are Monthly rates so we can convert those to Weekly Rates by multiplying with 12/52
b0 <- 0.5980              #monthly rate = 0.5980 
d0 <- 1/5                 #monthly rate = 1/5 
alpha0 <- 8.33*10^(-4)    #monthly rate = 8.33*10^(-4)
beta0 <- 5.2*10^(-8)      #monthly rate = 5.2*10^(-8) 
KcarryCap0 <- 70          #value = 70 per Hectare (100x100m grid) 
lambda0 <- 90000          #monthly rate = 90000 
gamma0 <- 1/3             #monthly rate = 1/3
mu0 <- 0.375              #monthly rate = 0.375
k0 <- 1                   #value = 1

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
betarPositive = beta0*resource
betarNegative = beta0/resource
betarNull = beta0+(resource*0)
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
mur = mu0*resource
krPositive = k0*resource
krNegative = k0/resource
krNull = k0+(resource*0)
```

```{r Model - TEST DETER MONTHLY - Logistic Growth - Short - Host Immune System Wins 6 panel (alpha and mu_pos)}
#b, d, alpha, beta, lambda, mu, gamma, and k from Berding 1987
#Carrying Capacity estimated from Forbes 2014

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=69, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positiveered effect of Resources (beta & k & b)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k & b) 
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

#################################################################################################################################################################
  
  #Null effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positiveered effect of Resources (beta & k & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k & muPositive) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}


hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostPointsAlpha <- gather(hostEquilibriumAlpha, key="Parameter_Descriptions", value="Host_Population", -R)
hostsAlpha <- ggplot(data=hostPointsAlpha, aes(x=R)) +
  #scale_y_continuous(breaks=seq(30, 130, by=20)) +
  #expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

parasitePointsAlpha <- gather(parasiteEquilibriumAlpha, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesAlpha <- ggplot(data=parasitePointsAlpha, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsAlpha <- gather(pphEquilibriumAlpha, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphAlpha <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 180, by=20)) +
  #expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

hostPointsMuPositive <- gather(hostEquilibriumMuPositive, key="Parameter_Descriptions", value="Host_Population", -R)
hostsMuPositive <- ggplot(data=hostPointsMuPositive, aes(x=R)) +
  #scale_y_continuous(breaks=seq(30, 130, by=20)) +
  #expand_limits(y=c(30,130)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

parasitePointsMuPositive <- gather(parasiteEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesMuPositive <- ggplot(data=parasitePointsMuPositive, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsMuPositive <- gather(pphEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphMuPositive <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 180, by=20)) +
  #expand_limits(y=c(0,180)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsAlpha, pphAlpha, parasitesAlpha, hostsMuPositive, pphMuPositive, parasitesMuPositive, labels=NULL, ncol=3, nrow=2)
```

```{r - USE ME - DETER + Berding MONTHLY - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
resource <- seq(1, 2, by=0.05)

xstart <- c(H=69, P=1)
monthsBreeding <- (12*5) #One year is 12 months
time <- seq(1,monthsBreeding,by=1)

#Parameter Values - Many are Monthly rates so we can convert those to Weekly Rates by multiplying with 12/52
b0 <- 0.5980              #monthly rate = 0.5980 
d0 <- 1/5                 #monthly rate = 1/5 
alpha0 <- 7.94*10^(-3)    #monthly rate = 7.94*10^(-3) calculated from avg_daily_rate*365/12 [FROM BERDING]
beta0 <- 5.2*10^(-8)      #monthly rate = 5.2*10^(-8) 
KcarryCap0 <- 70          #value = 70 per Hectare (100x100m grid) 
lambda0 <- 90000          #monthly rate = 90000 
gamma0 <- 1/3             #monthly rate = 1/3
mu0 <- 0.375              #monthly rate = 0.375
k0 <- 1                   #value = 1

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
betarPositive = beta0*resource
betarNegative = beta0/resource
betarNull = beta0+(resource*0)
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
murPositive = mu0*resource
murNegative = mu0/resource
krPositive = k0*resource
krNegative = k0/resource
krNull = k0+(resource*0)
```

```{r Model - DETER + Berding MONTHLY - Logistic Growth - Short - Host Immune System Wins 6 panel (alpha and mu_pos)}
#b, d, beta, lambda, mu, gamma, and k from Berding 1987
#Alpha from Berding 1987

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=69, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positive effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

#################################################################################################################################################################
  
  #Null effect of Resources (beta & k) with muPositive
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positive effect of Resources (beta & k) with muPositive
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k) with muPositive 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}


hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostPointsAlpha <- gather(hostEquilibriumAlpha, key="Parameter_Descriptions", value="Host_Population", -R)
hostsAlpha <- ggplot(data=hostPointsAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 70, by=10)) +
  expand_limits(y=c(30,70)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

parasitePointsAlpha <- gather(parasiteEquilibriumAlpha, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesAlpha <- ggplot(data=parasitePointsAlpha, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsAlpha <- gather(pphEquilibriumAlpha, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphAlpha <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 60, by=15)) +
  expand_limits(y=c(0,60)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

hostPointsMuPositive <- gather(hostEquilibriumMuPositive, key="Parameter_Descriptions", value="Host_Population", -R)
hostsMuPositive <- ggplot(data=hostPointsMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 70, by=10)) +
  expand_limits(y=c(30,70)) +
  geom_line(aes(y=Host_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) +
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

parasitePointsMuPositive <- gather(parasiteEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasite_Population", -R)
parasitesMuPositive <- ggplot(data=parasitePointsMuPositive, aes(x=R)) + 
  #scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
  #expand_limits(y=c(0,7000)) +
  geom_line(aes(y=Parasite_Population, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasite Population"))) +
  ggtitle(" ") + 
  theme_bw()

pphPointsMuPositive <- gather(pphEquilibriumMuPositive, key="Parameter_Descriptions", value="Parasites_per_Host", -R)
pphMuPositive <- ggplot(data=pphPointsMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 60, by=15)) +
  expand_limits(y=c(0,60)) +
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=Parameter_Descriptions), show.legend=FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

plotForLegend <- ggplot(data=pphPointsAlpha, aes(x=R)) + 
  geom_line(aes(y=Parasites_per_Host, group=Parameter_Descriptions, col=legendParameters$Effected_Parameter)) +
  labs(col="Effect on Infection Parameters") +
  theme_bw()
legendPlot <- cowplot::get_legend(plotForLegend)

plot_grid(hostsAlpha, pphAlpha, parasitesAlpha, hostsMuPositive, pphMuPositive, parasitesMuPositive, labels=NULL, ncol=3, nrow=2)

plot_grid(hostsAlpha, pphAlpha, hostsMuPositive, pphMuPositive, labels=NULL, ncol=2, nrow=2)
```

```{r Model - USE ME - DETER + Berding MONTHLY - Logistic Growth - Short - Host Immune System Wins 6 panel (alpha and mu_pos)}
#b, d, beta, lambda, mu, gamma, and k from Berding 1987
#Alpha from Berding 1987

#Creating empty vectors
equilibriumH_NullAlpha <- c()
equilibriumP_NullAlpha <- c()
tmpNullAlpha <- c()
equilibriumH_PositiveAlpha <- c()
equilibriumP_PositiveAlpha <- c()
tmpPositiveAlpha <- c()
equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_NullMu <- c()
equilibriumP_NullMu <- c()
tmpNullMu <- c()
equilibriumH_PositiveMu <- c()
equilibriumP_PositiveMu <- c()
tmpPositiveMu <- c()
equilibriumH_NegativeMu <- c()
equilibriumP_NegativeMu <- c()
tmpNegativeMu <- c()

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=69, P=1) #Resets the initial parameter values

  #Null effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullAlpha[length(equilibriumH_NullAlpha)+1] <- tmpNullAlpha$H[length(tmpNullAlpha$H)]
  equilibriumP_NullAlpha[length(equilibriumP_NullAlpha)+1] <- tmpNullAlpha$P[length(tmpNullAlpha$P)]
  
  #Positive effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveAlpha[length(equilibriumH_PositiveAlpha)+1] <- tmpPositiveAlpha$H[length(tmpPositiveAlpha$H)]
  equilibriumP_PositiveAlpha[length(equilibriumP_PositiveAlpha)+1] <- tmpPositiveAlpha$P[length(tmpPositiveAlpha$P)]
  
  #Negative effect of Resources (beta & k) with alpha
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

#################################################################################################################################################################
  
  #Null effect of Resources (beta & k) with muPositive
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNull[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNull[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNullMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NullMu[length(equilibriumH_NullMu)+1] <- tmpNullMu$H[length(tmpNullMu$H)]
  equilibriumP_NullMu[length(equilibriumP_NullMu)+1] <- tmpNullMu$P[length(tmpNullMu$P)]
  
  #Positive effect of Resources (beta & k) with muPositive
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMu[length(equilibriumH_PositiveMu)+1] <- tmpPositiveMu$H[length(tmpPositiveMu$H)]
  equilibriumP_PositiveMu[length(equilibriumP_PositiveMu)+1] <- tmpPositiveMu$P[length(tmpPositiveMu$P)]
  
  #Negative effect of Resources (beta & k) with muPositive 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative[i]
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krNegative[i]
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMu <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMu[length(equilibriumH_NegativeMu)+1] <- tmpNegativeMu$H[length(tmpNegativeMu$H)]
  equilibriumP_NegativeMu[length(equilibriumP_NegativeMu)+1] <- tmpNegativeMu$P[length(tmpNegativeMu$P)]

}


hostEquilibriumAlpha <- data.frame(R=resource,
                              H_NegativeAlpha=equilibriumH_NegativeAlpha,
                              H_NullAlpha=equilibriumH_NullAlpha,
                              H_PositiveAlpha=equilibriumH_PositiveAlpha
                              )

parasiteEquilibriumAlpha <- data.frame(R=resource,
                               P_NegativeAlpha=equilibriumP_NegativeAlpha,
                               P_NullAlpha=equilibriumP_NullAlpha,
                               P_PositiveAlpha=equilibriumP_PositiveAlpha
                               )

pphEquilibriumAlpha <- data.frame(R=resource,
                             PpH_NegativeAlpha=equilibriumP_NegativeAlpha/equilibriumH_NegativeAlpha,
                             PpH_NullAlpha=equilibriumP_NullAlpha/equilibriumH_NullAlpha,
                             PpH_PositiveAlpha=equilibriumP_PositiveAlpha/equilibriumH_PositiveAlpha
                             )

hostEquilibriumMuPositive <- data.frame(R=resource,
                              H_NegativeMu=equilibriumH_NegativeMu,
                              H_NullMu=equilibriumH_NullMu,
                              H_PositiveMu=equilibriumH_PositiveMu
                              )

parasiteEquilibriumMuPositive <- data.frame(R=resource,
                               P_NegativeMu=equilibriumP_NegativeMu,
                               P_NullMu=equilibriumP_NullMu,
                               P_PositiveMu=equilibriumP_PositiveMu
                               )
                               

pphEquilibriumMuPositive <- data.frame(R=resource,
                             PpH_NegativeMu=equilibriumP_NegativeMu/equilibriumH_NegativeMu,
                             PpH_NullMu=equilibriumP_NullMu/equilibriumH_NullMu,
                             PpH_PositiveMu=equilibriumP_PositiveMu/equilibriumH_PositiveMu
                             )

legendParameters <- data.frame(Effected_Parameter = c(replicate(21, "Negative"),
                                                      replicate(21, "Null"),
                                                      replicate(21, "Positive")
                                                      )
                               )

#Graphing
hostsAlpha <- ggplot(data=hostEquilibriumAlpha, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 70, by=10)) +
  expand_limits(y=c(30,70)) +
  geom_line(aes(y=H_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=H_NullAlpha), color="black", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=H_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) +    
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Decreasing Parasite Virulence") + 
  theme_bw()

#parasitesAlpha <- ggplot(data=parasiteEquilibriumAlpha, aes(x=R)) + 
#  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
#  expand_limits(y=c(0,7000)) +
#  geom_line(aes(y=P_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
#  geom_line(aes(y=P_NullAlpha), color="black", show.legend = FALSE, size = 1.2) +
#  geom_line(aes(y=P_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) + 
#  labs(x = expression(bold("Resource Effect")),
#       y = expression(bold("Parasite Population"))) +
#  ggtitle(" ") + 
#  theme_bw()

pphAlpha <- ggplot(data=pphEquilibriumAlpha, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 60, by=15)) +
  expand_limits(y=c(0,60)) +
  geom_line(aes(y=PpH_NegativeAlpha), color="red", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=PpH_NullAlpha), color="black", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=PpH_PositiveAlpha), color="blue", show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

hostsMuPositive <- ggplot(data=hostEquilibriumMuPositive, aes(x=R)) +
  scale_y_continuous(breaks=seq(30, 70, by=10)) +
  expand_limits(y=c(30,70)) +
  geom_line(aes(y=H_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=H_NullMu), color="black", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=H_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Host Population"))) +
  ggtitle("Increasing Parasite Mortality") + 
  theme_bw()

#parasitesMuPositive <- ggplot(data=parasiteEquilibriumMuPositive, aes(x=R)) + 
#  scale_y_continuous(breaks=seq(0, 7000, by=1000)) +
#  expand_limits(y=c(0,7000)) +
#  geom_line(aes(y=P_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
#  geom_line(aes(y=P_NullMu), color="black", show.legend = FALSE, size = 1.2) +
#  geom_line(aes(y=P_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) +   
#  labs(x = expression(bold("Resource Effect")),
#       y = expression(bold("Parasite Population"))) +
#  ggtitle(" ") + 
#  theme_bw()

pphMuPositive <- ggplot(data=pphEquilibriumMuPositive, aes(x=R)) + 
  scale_y_continuous(breaks=seq(0, 60, by=15)) +
  expand_limits(y=c(0,60)) +
  geom_line(aes(y=PpH_NegativeMu), color="red", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=PpH_NullMu), color="black", show.legend = FALSE, size = 1.2) +
  geom_line(aes(y=PpH_PositiveMu), color="blue", show.legend = FALSE, size = 1.2) + 
  labs(x = expression(bold("Resource Effect")),
       y = expression(bold("Parasites per Host")),
       col="Effect on Infection Parameters") +
  ggtitle("60 Months (10 Seasons)") + 
  theme_bw()

#plot_grid(hostsAlpha, pphAlpha, parasitesAlpha, hostsMuPositive, pphMuPositive, parasitesMuPositive, labels=NULL, ncol=3, nrow=2)

plot_grid(hostsAlpha, pphAlpha, hostsMuPositive, pphMuPositive, labels=NULL, ncol=2, nrow=2)
```