---
title: "Untitled"
author: "Brendan Haile"
date: '2023-07-19'
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r Packages}
library(deSolve)
library(tidyverse)
library(cowplot)
```

```{r Function - Logistic Growth}
#Recreating the macroparasite function but with logistic growth

# list of parameters for quick reference
# b = per capita host birth rate
# d = per capita host mortality
# alpha = additional per capita host mortality due to parasite burden (P/H)*H
# beta = transmission (ingestion) rate of parasites by host
# lambda = external parasite production rate (per parasite)
# gamma = per capita loss rate of entl parasite stages
# mu = parasite mortality within hosts
# k = overdispersion parameter; measures parasite Dispersion (low k = highly aggregated in few hosts, high k = equally distributed among hosts)

macroParasiteLogistic <- function(t, x, parameters){
  H <- x[1]
  P <- x[2]
  with(                                   
       as.list(params),                   
       {                                  
         dH <- (b-d)*H*(1-(H/KcarryCap))-(alpha*P)
         dP <- (beta*H*lambda*P)/(gamma+beta*H) - P*(d+mu+alpha) - (P*P*alpha*(k+1))/(k*H)
         dXlist <- c(dH,dP)                
         list(dXlist)                         
       }
       )
}
```

```{r - DETER + Berding MONTHLY - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
foragingResource <- seq(1, 5, by=0.1)
resource <- seq(min(foragingResource), 10, by=0.1)

xstart <- c(H=69, P=1)
monthsBreeding <- (12*5) #One year is 12 months
time <- seq(1,monthsBreeding,by=1)

#Parameter Values 
b0 <- 0.5980              #monthly rate = 0.5980 
d0 <- 1/5                 #monthly rate = 1/5
alpha0 <- 7.94*10^(-3)    #monthly rate = 7.94*10^(-3) calculated from avg_daily_rate*365/12 [FROM BERDING]
beta0 <- 5.2*10^(-8)      #monthly rate = 5.2*10^(-8)
KcarryCap0 <- 70          #value = 70 per Hectare (100x100m grid)
lambda0 <- 90000          #monthly rate = 90000
gamma0 <- 1/3             #monthly rate = 1/3
mu0 <- 0.375              #monthly rate = 0.375
k0 <- 1                   #value = 1

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
murPositive = mu0*resource
murNegative = mu0/resource

betarPositive = beta0*foragingResource
betarNegative = beta0/foragingResource
betarNull = beta0+(foragingResource*0)
krPositive = k0*foragingResource
krNegative = k0/foragingResource
krNull = k0+(foragingResource*0)
```

```{r Model -  DETER + Berding MONTHLY - Logistic Growth - Finding resource breakpoints for when each NON-FORAGING parameter undoes the effects of FORAGING parameters on Hosts/Parasites per Host BUT we are varying BOTH resource effects}
#b, d, beta, lambda, mu, gamma, KcarryCap and k from Deter 2008
#Alpha from Berding 1987

#Creating empty vectors
equilibriumH_Baseline <- c()
equilibriumP_Baseline <- c()
tmpBaseline <- c()

#Creating Breakpoint Vectors
hostResourceBreakPointForB <- c()
pphResourceBreakPointForB <- c()
hostResourceBreakPointForD <- c()
pphResourceBreakPointForD <- c()
hostResourceBreakPointForKcarryCap <- c()
pphResourceBreakPointForKcarryCap <- c()
hostResourceBreakPointForAlpha <- c()           #when Resources start @ 1 this is the only one that doesn't work
pphResourceBreakPointForAlpha <- c()
hostResourceBreakPointForMuPositive <- c()
pphResourceBreakPointForMuPositive <- c()
hostResourceBreakPointForLambda <- c()
pphResourceBreakPointForLambda <- c()
hostResourceBreakPointForMuNegative <- c()
pphResourceBreakPointForMuNegative <- c()

#Creating ForagingResource Vectors (mostly just for organization)
hostForagingResourceForB <- c()
pphForagingResourceForB <- c()
hostForagingResourceForD <- c()
pphForagingResourceForD <- c()
hostForagingResourceForKcarryCap <- c()
pphForagingResourceForKcarryCap <- c()
hostForagingResourceForAlpha <- c()
pphForagingResourceForAlpha <- c()
hostForagingResourceForMuPositive <- c()
pphForagingResourceForMuPositive <- c()
hostForagingResourceForLambda <- c()
pphForagingResourceForLambda <- c()
hostForagingResourceForMuNegative <- c()
pphForagingResourceForMuNegative <- c()

#Baseline Scenario for Comparisons
b=b0
d=d0
alpha=alpha0
beta=beta0
lambda=lambda0
gamma=gamma0
mu=mu0
k=k0
KcarryCap = KcarryCap0
#Creating parameters & running model
params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
tmpBaseline <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
equilibriumH_Baseline[length(equilibriumH_Baseline)+1] <- tmpBaseline$H[length(tmpBaseline$H)]
equilibriumP_Baseline[length(equilibriumP_Baseline)+1] <- tmpBaseline$P[length(tmpBaseline$P)]


for (j in 1:length(foragingResource)){
  #Creating empty vectors (must be reset each time we select a new foragingResource level)
  equilibriumH_PositiveB <- c()
  equilibriumP_PositiveB <- c()
  tmpPositiveB <- c()
  equilibriumNonForagingResource_PositiveB <- c()
  equilibriumForagingResource_PositiveB <- c()
  equilibriumH_NegativeB <- c()
  equilibriumP_NegativeB <- c()
  tmpNegativeB <- c()
  equilibriumNonForagingResource_NegativeB <- c()
  equilibriumForagingResource_NegativeB <- c()
  
  equilibriumH_NegativeD <- c()
  equilibriumP_NegativeD <- c()
  tmpNegativeD <- c()
  equilibriumNonForagingResource_NegativeD <- c()
  equilibriumForagingResource_NegativeD <- c()
  
  equilibriumH_PositiveKcarryCap <- c()
  equilibriumP_PositiveKcarryCap <- c()
  tmpPositiveKcarryCap <- c()
  equilibriumNonForagingResource_PositiveKcarryCap <- c()
  equilibriumForagingResource_PositiveKcarryCap <- c()
  equilibriumH_NegativeKcarryCap <- c()
  equilibriumP_NegativeKcarryCap <- c()
  tmpNegativeKcarryCap <- c()
  equilibriumNonForagingResource_NegativeKcarryCap <- c()
  equilibriumForagingResource_NegativeKcarryCap <- c()
  
  equilibriumH_NegativeAlpha <- c()
  equilibriumP_NegativeAlpha <- c()
  tmpNegativeAlpha <- c()
  equilibriumNonForagingResource_NegativeAlpha <- c()
  equilibriumForagingResource_NegativeAlpha <- c()
  
  equilibriumH_PositiveMuPositive <- c()
  equilibriumP_PositiveMuPositive <- c()
  tmpPositiveMuPositive <- c()
  equilibriumNonForagingResource_PositiveMuPositive <- c()
  equilibriumForagingResource_PositiveMuPositive <- c()
  
  equilibriumH_NegativeLambda <- c()
  equilibriumP_NegativeLambda <- c()
  tmpNegativeLambda <- c()
  equilibriumNonForagingResource_NegativeLambda <- c()
  equilibriumForagingResource_NegativeLambda <- c()
  
  equilibriumH_NegativeMuNegative <- c()
  equilibriumP_NegativeMuNegative <- c()
  tmpNegativeMuNegative <- c()
  equilibriumNonForagingResource_NegativeMuNegative <- c()
  equilibriumForagingResource_NegativeMuNegative <- c()
  
  #Creating "finder" variables (must be reset each time we select a new foragingResource level)
  hostFirstB <- TRUE
  pphFirstB <- TRUE
  hostFirstD <- TRUE
  pphFirstD <- TRUE
  hostFirstKcarryCap <- TRUE
  pphFirstKcarryCap <- TRUE
  hostFirstAlpha <- TRUE
  pphFirstAlpha <- TRUE
  hostFirstMuPositive <- TRUE
  pphFirstMuPositive <- TRUE
  hostFirstLambda <- TRUE
  pphFirstLambda <- TRUE
  hostFirstMuNegative <- TRUE
  pphFirstMuNegative <- TRUE

  
  for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
    xstart <- c(H=69, P=1) #Resets the initial parameter values

#[NOTE: This only works when the DIRECTIONALITY of FORAGING and NON-FORAGING PARAMETERS are OPPOSITE]
#Allowing resources to effect non-foraging paramaters (b, d, and KcarryCap) improves the host population [Look at the % Change Effect of baseline]
#Therefore we must select the Resource Effect on Foraging parameters that has the OPPOSITE EFFECT
#There is a POSITIVE effect of resources on Foraging Parameters (beta & k) which is WORSE FOR HOSTS

    #Negative effect of Resources (beta & k) with Positive effect (b)
    b=br[i]
    d=d0
    alpha=alpha0
    beta=betarNegative[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krNegative[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeB <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeB[length(equilibriumH_NegativeB)+1] <- tmpNegativeB$H[length(tmpNegativeB$H)]
    equilibriumP_NegativeB[length(equilibriumP_NegativeB)+1] <- tmpNegativeB$P[length(tmpNegativeB$P)]
    equilibriumForagingResource_NegativeB[length(equilibriumForagingResource_NegativeB)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeB[length(equilibriumNonForagingResource_NegativeB)+1] <- resource[i]
    
    #Positive effect of Resources (beta & k & b)
    b=br[i]
    d=d0
    alpha=alpha0
    beta=betarPositive[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krPositive[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpPositiveB <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_PositiveB[length(equilibriumH_PositiveB)+1] <- tmpPositiveB$H[length(tmpPositiveB$H)]
    equilibriumP_PositiveB[length(equilibriumP_PositiveB)+1] <- tmpPositiveB$P[length(tmpPositiveB$P)]
    equilibriumForagingResource_PositiveB[length(equilibriumForagingResource_PositiveB)+1] <- foragingResource[j]
    equilibriumNonForagingResource_PositiveB[length(equilibriumNonForagingResource_PositiveB)+1] <- resource[i]
    
    #Checking percentage change
    hostOriginalPctChangeForB <- (equilibriumH_PositiveB[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForB <- (equilibriumH_PositiveB[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
      
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeB[1]/equilibriumH_NegativeB[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeB[i]/equilibriumH_NegativeB[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForB <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForB <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstB==TRUE & (sign(hostOriginalPctChangeForB)==-1 & hostCurrentPctChangeForB>0)){
      hostFirstB <- FALSE
      hostResourceBreakPointForB <- append(hostResourceBreakPointForB, resource[i])
      hostForagingResourceForB <- append(hostForagingResourceForB, foragingResource[j])
    } else if (hostFirstB==TRUE & (sign(hostOriginalPctChangeForB)==1 & hostCurrentPctChangeForB<0)){
      hostFirstB <- FALSE
      hostResourceBreakPointForB <- append(hostResourceBreakPointForB, resource[i])      
      hostForagingResourceForB <- append(hostForagingResourceForB, foragingResource[j])
    } else {
      hostResourceBreakPointForB <- hostResourceBreakPointForB
      hostForagingResourceForB <- hostForagingResourceForB
    }
  
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstB==TRUE & (sign(pphOriginalPctChangeForB)==-1 & pphCurrentPctChangeForB>0)){
      pphFirstB <- FALSE
      pphResourceBreakPointForB <- append(pphResourceBreakPointForB, resource[i])
      pphForagingResourceForB <- append(pphForagingResourceForB, foragingResource[j])
    } else if (pphFirstB==TRUE & (sign(pphOriginalPctChangeForB)==1 & pphCurrentPctChangeForB<0)){
      pphFirstB <- FALSE
      pphResourceBreakPointForB <- append(pphResourceBreakPointForB, resource[i])
      pphForagingResourceForB <- append(pphForagingResourceForB, foragingResource[j])
      } else {
      pphResourceBreakPointForB <- pphResourceBreakPointForB
      pphForagingResourceForB <- pphForagingResourceForB

    }
        
    #########################################################################################################################################
    
    #Negative effect of Resources (beta & k & d) 
    b=b0
    d=dr[i]
    alpha=alpha0
    beta=betarNegative[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krNegative[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeD <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeD[length(equilibriumH_NegativeD)+1] <- tmpNegativeD$H[length(tmpNegativeD$H)]
    equilibriumP_NegativeD[length(equilibriumP_NegativeD)+1] <- tmpNegativeD$P[length(tmpNegativeD$P)]
    equilibriumForagingResource_NegativeD[length(equilibriumForagingResource_NegativeD)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeD[length(equilibriumNonForagingResource_NegativeD)+1] <- resource[i]
        
    #Checking percentage change
    hostOriginalPctChangeForD <- (equilibriumH_NegativeD[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForD <- (equilibriumH_NegativeD[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeD[1]/equilibriumH_NegativeD[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeD[i]/equilibriumH_NegativeD[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForD <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForD <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstD==TRUE & (sign(hostOriginalPctChangeForD)==-1 & hostCurrentPctChangeForD>0)){
      hostFirstD <- FALSE
      hostResourceBreakPointForD <- append(hostResourceBreakPointForD, resource[i])
      hostForagingResourceForD <- append(hostForagingResourceForD, foragingResource[j])
      } else if (hostFirstD==TRUE & (sign(hostOriginalPctChangeForD)==1 & hostCurrentPctChangeForD<0)){
      hostFirstD <- FALSE
      hostResourceBreakPointForD <- append(hostResourceBreakPointForD, resource[i])
      hostForagingResourceForD <- append(hostForagingResourceForD, foragingResource[j])
      } else {
      hostResourceBreakPointForD <- hostResourceBreakPointForD
      hostForagingResourceForD <- hostForagingResourceForD
    }
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstD==TRUE & (sign(pphOriginalPctChangeForD)==-1 & pphCurrentPctChangeForD>0)){
      pphFirstD <- FALSE
      pphResourceBreakPointForD <- append(pphResourceBreakPointForD, resource[i])
      pphForagingResourceForD <- append(pphForagingResourceForD, foragingResource[j])
      } else if (pphFirstD==TRUE & (sign(pphOriginalPctChangeForD)==1 & pphCurrentPctChangeForD<0)){
      pphFirstD <- FALSE
      pphResourceBreakPointForD <- append(pphResourceBreakPointForD, resource[i])
      pphForagingResourceForD <- append(pphForagingResourceForD, foragingResource[j])
      } else {
      pphResourceBreakPointForD <- pphResourceBreakPointForD
      pphForagingResourceForD <- pphForagingResourceForD

    }
    
  #########################################################################################################################################
    
    #Positive effect of Resources (beta & k & KcarryCap)
    b=b0
    d=d0
    alpha=alpha0
    beta=betarPositive[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krPositive[j]
    KcarryCap = KcarryCapr[i]
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpPositiveKcarryCap <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_PositiveKcarryCap[length(equilibriumH_PositiveKcarryCap)+1] <- tmpPositiveKcarryCap$H[length(tmpPositiveKcarryCap$H)]
    equilibriumP_PositiveKcarryCap[length(equilibriumP_PositiveKcarryCap)+1] <- tmpPositiveKcarryCap$P[length(tmpPositiveKcarryCap$P)]
    equilibriumForagingResource_PositiveKcarryCap[length(equilibriumForagingResource_PositiveKcarryCap)+1] <- foragingResource[j]
    equilibriumNonForagingResource_PositiveKcarryCap[length(equilibriumNonForagingResource_PositiveKcarryCap)+1] <- resource[i]
    
    #Negative effect of Resources (beta & k) with Positive effect (KcarryCap) 
    b=b0
    d=d0
    alpha=alpha0
    beta=betarNegative[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krNegative[j]
    KcarryCap = KcarryCapr[i]
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeKcarryCap <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeKcarryCap[length(equilibriumH_NegativeKcarryCap)+1] <- tmpNegativeKcarryCap$H[length(tmpNegativeKcarryCap$H)]
    equilibriumP_NegativeKcarryCap[length(equilibriumP_NegativeKcarryCap)+1] <- tmpNegativeKcarryCap$P[length(tmpNegativeKcarryCap$P)]
    equilibriumForagingResource_NegativeKcarryCap[length(equilibriumForagingResource_NegativeKcarryCap)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeKcarryCap[length(equilibriumNonForagingResource_NegativeKcarryCap)+1] <- resource[i]
    
    #Checking percentage change
    hostOriginalPctChangeForKcarryCap <- (equilibriumH_PositiveKcarryCap[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForKcarryCap <- (equilibriumH_PositiveKcarryCap[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeKcarryCap[1]/equilibriumH_NegativeKcarryCap[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeKcarryCap[i]/equilibriumH_NegativeKcarryCap[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForKcarryCap <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForKcarryCap <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstKcarryCap==TRUE & (sign(hostOriginalPctChangeForKcarryCap)==-1 & hostCurrentPctChangeForKcarryCap>0)){
      hostFirstKcarryCap <- FALSE
      hostResourceBreakPointForKcarryCap <- append(hostResourceBreakPointForKcarryCap, resource[i])
      hostForagingResourceForKcarryCap <- append(hostForagingResourceForKcarryCap, foragingResource[j])
      } else if (hostFirstKcarryCap==TRUE & (sign(hostOriginalPctChangeForKcarryCap)==1 & hostCurrentPctChangeForKcarryCap<0)){
      hostFirstKcarryCap <- FALSE
      hostResourceBreakPointForKcarryCap <- append(hostResourceBreakPointForKcarryCap, resource[i])
      hostForagingResourceForKcarryCap <- append(hostForagingResourceForKcarryCap, foragingResource[j])
      } else {
      hostResourceBreakPointForKcarryCap <- hostResourceBreakPointForKcarryCap
      hostForagingResourceForKcarryCap <- hostForagingResourceForKcarryCap
      }
  
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstKcarryCap==TRUE & (sign(pphOriginalPctChangeForKcarryCap)==-1 & pphCurrentPctChangeForKcarryCap>0)){
      pphFirstKcarryCap <- FALSE
      pphResourceBreakPointForKcarryCap <- append(pphResourceBreakPointForKcarryCap, resource[i])
      pphForagingResourceForKcarryCap <- append(pphForagingResourceForKcarryCap, foragingResource[j])
      } else if (pphFirstKcarryCap==TRUE & (sign(pphOriginalPctChangeForKcarryCap)==1 & pphCurrentPctChangeForKcarryCap<0)){
      pphFirstKcarryCap <- FALSE
      pphResourceBreakPointForKcarryCap <- append(pphResourceBreakPointForKcarryCap, resource[i])
      pphForagingResourceForKcarryCap <- append(pphForagingResourceForKcarryCap, foragingResource[j])
      } else {
      pphResourceBreakPointForKcarryCap <- pphResourceBreakPointForKcarryCap
      pphForagingResourceForKcarryCap <- pphForagingResourceForKcarryCap
      }
  
  ########################################################################################################################################
    
    #Negative effect of Resources (beta, k, & alpha)
    b=b0
    d=d0
    alpha=alphar[i]
    beta=betarNegative[j]
    lambda=lambda0
    gamma=gamma0
    mu=mu0
    k=krNegative[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
    equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]
    equilibriumForagingResource_NegativeAlpha[length(equilibriumForagingResource_NegativeAlpha)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeAlpha[length(equilibriumNonForagingResource_NegativeAlpha)+1] <- resource[i]
      
    #Checking percentage change
    hostOriginalPctChangeForAlpha <- (equilibriumH_NegativeAlpha[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForAlpha <- (equilibriumH_NegativeAlpha[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeAlpha[1]/equilibriumH_NegativeAlpha[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeAlpha[i]/equilibriumH_NegativeAlpha[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForAlpha <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForAlpha <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstAlpha==TRUE & (sign(hostOriginalPctChangeForAlpha)==-1 & hostCurrentPctChangeForAlpha>0)){
      hostFirstAlpha <- FALSE
      hostResourceBreakPointForAlpha <- append(hostResourceBreakPointForAlpha, resource[i])
      hostForagingResourceForAlpha <- append(hostForagingResourceForAlpha, foragingResource[j])
      } else if (hostFirstAlpha==TRUE & (sign(hostOriginalPctChangeForAlpha)==1 & hostCurrentPctChangeForAlpha<0)){
      hostFirstAlpha <- FALSE
      hostResourceBreakPointForAlpha <- append(hostResourceBreakPointForAlpha, resource[i])
      hostForagingResourceForAlpha <- append(hostForagingResourceForAlpha, foragingResource[j])
      } else {
      hostResourceBreakPointForAlpha <- hostResourceBreakPointForAlpha
      hostForagingResourceForAlpha <- hostForagingResourceForAlpha
    } 
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstAlpha==TRUE & (sign(pphOriginalPctChangeForAlpha)==-1 & pphCurrentPctChangeForAlpha>0)){
      pphFirstAlpha <- FALSE
      pphResourceBreakPointForAlpha <- append(pphResourceBreakPointForAlpha, resource[i])
      pphForagingResourceForAlpha <- append(pphForagingResourceForAlpha, foragingResource[j])
      } else if (pphFirstAlpha==TRUE & (sign(pphOriginalPctChangeForAlpha)==1 & pphCurrentPctChangeForAlpha<0)){
      pphFirstAlpha <- FALSE
      pphResourceBreakPointForAlpha <- append(pphResourceBreakPointForAlpha, resource[i])
      pphForagingResourceForAlpha <- append(pphForagingResourceForAlpha, foragingResource[j])
      } else {
      pphResourceBreakPointForAlpha <- pphResourceBreakPointForAlpha
      pphForagingResourceForAlpha <- pphForagingResourceForAlpha
    }
    
  ########################################################################################################################################
  
    #Positive effect of Resources (beta, k, & muPositive)
    b=b0
    d=d0
    alpha=alpha0
    beta=betarPositive[j]
    lambda=lambda0
    gamma=gamma0
    mu=murPositive[i]
    k=krPositive[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpPositiveMuPositive <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_PositiveMuPositive[length(equilibriumH_PositiveMuPositive)+1] <- tmpPositiveMuPositive$H[length(tmpPositiveMuPositive$H)]
    equilibriumP_PositiveMuPositive[length(equilibriumP_PositiveMuPositive)+1] <- tmpPositiveMuPositive$P[length(tmpPositiveMuPositive$P)]
    equilibriumForagingResource_PositiveMuPositive[length(equilibriumForagingResource_PositiveMuPositive)+1] <- foragingResource[j]
    equilibriumNonForagingResource_PositiveMuPositive[length(equilibriumNonForagingResource_PositiveMuPositive)+1] <- resource[i]
    
    #Checking percentage change
    hostOriginalPctChangeForMuPositive <- (equilibriumH_PositiveMuPositive[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForMuPositive <- (equilibriumH_PositiveMuPositive[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_PositiveMuPositive[1]/equilibriumH_PositiveMuPositive[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_PositiveMuPositive[i]/equilibriumH_PositiveMuPositive[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForMuPositive <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForMuPositive <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstMuPositive==TRUE & (sign(hostOriginalPctChangeForMuPositive)==-1 & hostCurrentPctChangeForMuPositive>0)){
      hostFirstMuPositive <- FALSE
      hostResourceBreakPointForMuPositive <- append(hostResourceBreakPointForMuPositive, resource[i])
      hostForagingResourceForMuPositive <- append(hostForagingResourceForMuPositive, foragingResource[j])
      } else if (hostFirstMuPositive==TRUE & (sign(hostOriginalPctChangeForMuPositive)==1 & hostCurrentPctChangeForMuPositive<0)){
      hostFirstMuPositive <- FALSE
      hostResourceBreakPointForMuPositive <- append(hostResourceBreakPointForMuPositive, resource[i])
      hostForagingResourceForMuPositive <- append(hostForagingResourceForMuPositive, foragingResource[j])
      } else {
      hostResourceBreakPointForMuPositive <- hostResourceBreakPointForMuPositive      
      hostForagingResourceForMuPositive <- hostForagingResourceForMuPositive
    } 
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstMuPositive==TRUE & (sign(pphOriginalPctChangeForMuPositive)==-1 & pphCurrentPctChangeForMuPositive>0)){
      pphFirstMuPositive <- FALSE
      pphResourceBreakPointForMuPositive <- append(pphResourceBreakPointForMuPositive, resource[i])
      pphForagingResourceForMuPositive <- append(pphForagingResourceForMuPositive, foragingResource[j])
      } else if (pphFirstMuPositive==TRUE & (sign(pphOriginalPctChangeForMuPositive)==1 & pphCurrentPctChangeForMuPositive<0)){
      pphFirstMuPositive <- FALSE
      pphResourceBreakPointForMuPositive <- append(pphResourceBreakPointForMuPositive, resource[i])
      pphForagingResourceForMuPositive <- append(pphForagingResourceForMuPositive, foragingResource[j])
      } else {
      pphResourceBreakPointForMuPositive <- pphResourceBreakPointForMuPositive      
      pphForagingResourceForMuPositive <- pphForagingResourceForMuPositive
    }
    
  ########################################################################################################################################
    
    #Negative effect of Resources (beta & k & lambda) 
    b=b0
    d=d0
    alpha=alpha0
    beta=betarNegative[j]
    lambda=lambdar[i]
    gamma=gamma0
    mu=mu0
    k=krNegative[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeLambda <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeLambda[length(equilibriumH_NegativeLambda)+1] <- tmpNegativeLambda$H[length(tmpNegativeLambda$H)]
    equilibriumP_NegativeLambda[length(equilibriumP_NegativeLambda)+1] <- tmpNegativeLambda$P[length(tmpNegativeLambda$P)]
    equilibriumForagingResource_NegativeLambda[length(equilibriumForagingResource_NegativeLambda)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeLambda[length(equilibriumNonForagingResource_NegativeLambda)+1] <- resource[i]
    
    #Checking percentage change
    hostOriginalPctChangeForLambda <- (equilibriumH_NegativeLambda[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForLambda <- (equilibriumH_NegativeLambda[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeLambda[1]/equilibriumH_NegativeLambda[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeLambda[i]/equilibriumH_NegativeLambda[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForLambda <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForLambda <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstLambda==TRUE & (sign(hostOriginalPctChangeForLambda)==-1 & hostCurrentPctChangeForLambda>0)){
      hostFirstLambda <- FALSE
      hostResourceBreakPointForLambda <- append(hostResourceBreakPointForLambda, resource[i])
      hostForagingResourceForLambda <- append(hostForagingResourceForLambda, foragingResource[j])
      } else if (hostFirstLambda==TRUE & (sign(hostOriginalPctChangeForLambda)==1 & hostCurrentPctChangeForLambda<0)){
      hostFirstLambda <- FALSE
      hostResourceBreakPointForLambda <- append(hostResourceBreakPointForLambda, resource[i])
      hostForagingResourceForLambda <- append(hostForagingResourceForLambda, foragingResource[j])
      } else {
      hostResourceBreakPointForLambda <- hostResourceBreakPointForLambda      
      hostForagingResourceForLambda <- hostForagingResourceForLambda
    } 
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstLambda==TRUE & (sign(pphOriginalPctChangeForLambda)==-1 & pphCurrentPctChangeForLambda>0)){
      pphFirstLambda <- FALSE
      pphResourceBreakPointForLambda <- append(pphResourceBreakPointForLambda, resource[i])
      pphForagingResourceForLambda <- append(pphForagingResourceForLambda, foragingResource[j])
      } else if (pphFirstLambda==TRUE & (sign(pphOriginalPctChangeForLambda)==1 & pphCurrentPctChangeForLambda<0)){
      pphFirstLambda <- FALSE
      pphResourceBreakPointForLambda <- append(pphResourceBreakPointForLambda, resource[i])
      pphForagingResourceForLambda <- append(pphForagingResourceForLambda, foragingResource[j])
      } else {
      pphResourceBreakPointForLambda<- pphResourceBreakPointForLambda     
      pphForagingResourceForLambda <- pphForagingResourceForLambda
    }
    
  ########################################################################################################################################
    
    #Negative effect of Resources (beta & k & muNegative) 
    b=b0
    d=d0
    alpha=alpha0
    beta=betarNegative[j]
    lambda=lambda0
    gamma=gamma0
    mu=murNegative[i]
    k=krNegative[j]
    KcarryCap = KcarryCap0
    #Creating parameters & running model
    params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
    tmpNegativeMuNegative <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
    equilibriumH_NegativeMuNegative[length(equilibriumH_NegativeMuNegative)+1] <- tmpNegativeMuNegative$H[length(tmpNegativeMuNegative$H)]
    equilibriumP_NegativeMuNegative[length(equilibriumP_NegativeMuNegative)+1] <- tmpNegativeMuNegative$P[length(tmpNegativeMuNegative$P)]
    equilibriumForagingResource_NegativeMuNegative[length(equilibriumForagingResource_NegativeMuNegative)+1] <- foragingResource[j]
    equilibriumNonForagingResource_NegativeMuNegative[length(equilibriumNonForagingResource_NegativeMuNegative)+1] <- resource[i]
        
    #Checking percentage change
    hostOriginalPctChangeForMuNegative <- (equilibriumH_NegativeMuNegative[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    hostCurrentPctChangeForMuNegative <- (equilibriumH_NegativeMuNegative[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
    
    pphOriginalPctChangeTerm1 <- equilibriumP_NegativeMuNegative[1]/equilibriumH_NegativeMuNegative[1]
    pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphCurrentPctChangeTerm1 <- equilibriumP_NegativeMuNegative[i]/equilibriumH_NegativeMuNegative[i]
    pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
    
    pphOriginalPctChangeForMuNegative <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
    pphCurrentPctChangeForMuNegative <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (hostFirstMuNegative==TRUE & (sign(hostOriginalPctChangeForMuNegative)== -1 & hostCurrentPctChangeForMuNegative>0)){
      hostFirstMuNegative <- FALSE
      hostResourceBreakPointForMuNegative <- append(hostResourceBreakPointForMuNegative, resource[i])
      hostForagingResourceForMuNegative <- append(hostForagingResourceForMuNegative, foragingResource[j])
      } else if (hostFirstMuNegative==TRUE & (sign(hostOriginalPctChangeForMuNegative)== 1 & hostCurrentPctChangeForMuNegative<0)){
      hostFirstMuNegative <- FALSE
      hostResourceBreakPointForMuNegative <- append(hostResourceBreakPointForMuNegative, resource[i])
      hostForagingResourceForMuNegative <- append(hostForagingResourceForMuNegative, foragingResource[j])
      } else {
      hostResourceBreakPointForMuNegative <- hostResourceBreakPointForMuNegative      
      hostForagingResourceForMuNegative <- hostForagingResourceForMuNegative
    } 
    
    #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
    if (pphFirstMuNegative==TRUE & (sign(pphOriginalPctChangeForMuNegative)== -1 & pphCurrentPctChangeForMuNegative>0)){
      pphFirstMuNegative <- FALSE
      pphResourceBreakPointForMuNegative  <- append(pphResourceBreakPointForMuNegative , resource[i])
      pphForagingResourceForMuNegative  <- append(pphForagingResourceForMuNegative , foragingResource[j])
      } else if (pphFirstMuNegative==TRUE & (sign(pphOriginalPctChangeForMuNegative)== 1 & pphCurrentPctChangeForMuNegative<0)){
      pphFirstMuNegative <- FALSE
      pphResourceBreakPointForMuNegative  <- append(pphResourceBreakPointForMuNegative , resource[i])
      pphForagingResourceForMuNegative  <- append(pphForagingResourceForMuNegative , foragingResource[j])
      } else {
      pphResourceBreakPointForMuNegative <- pphResourceBreakPointForMuNegative      
      pphForagingResourceForMuNegative  <- pphForagingResourceForMuNegative 
    }
  
  }
  
}

```

```{r - Linear Regression to find equation for resourceBreakpoints}
#We can use slope of these regressions as the "sensitivity" of a nonForagingParameter to resource subsidy

hostBirthLM <- lm(hostResourceBreakPointForB ~ hostForagingResourceForB)
summary(hostBirthLM)
  #breakPoint = -4.67727 + hostForaging*4.84545 
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

hostDeathLM <- lm(hostResourceBreakPointForD ~ hostForagingResourceForD)
summary(hostDeathLM)
  #breakPoint = -4.67727 + hostForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

hostCarryingCapacityLM <- lm(hostResourceBreakPointForKcarryCap ~ hostForagingResourceForKcarryCap)
summary(hostCarryingCapacityLM)
  #breakPoint = -4.67727 + hostForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992


#hostParasiteVirulenceLM <- lm(hostResourceBreakPointForAlpha ~ hostForagingResourceForAlpha)
#summary(hostParasiteVirulenceLM)
  #Only version that doesn't work. Null points for both. It fails to reach a breakpoint.

hostMuPositiveLM <- lm(hostResourceBreakPointForMuPositive ~ hostForagingResourceForMuPositive)
summary(hostMuPositiveLM)
  #breakPoint = -0.916734 + hostForaging*2.060081
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9997

hostLambdaLM <- lm(hostResourceBreakPointForLambda ~ hostForagingResourceForLambda)
summary(hostLambdaLM)
  #breakPoint = -1.30202 + hostForaging*1.70565
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9963

hostMuNegativeLM <- lm(hostResourceBreakPointForMuNegative ~ hostForagingResourceForMuNegative)
summary(hostMuNegativeLM)
  #breakPoint = -0.916734 + hostForaging*2.060081
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9997

######################################################################################################

pphBirthLM <- lm(pphResourceBreakPointForB ~ pphForagingResourceForB)
summary(pphBirthLM)
  #breakPoint = -4.67727 + pphForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

pphDeathLM <- lm(pphResourceBreakPointForD ~ pphForagingResourceForD)
summary(pphDeathLM)
  #breakPoint = -4.67727 + pphForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

pphCarryingCapacityLM <- lm(pphResourceBreakPointForKcarryCap ~ pphForagingResourceForKcarryCap)
summary(pphCarryingCapacityLM)
  #breakPoint = -4.67727 + pphForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

pphParasiteVirulenceLM <- lm(pphResourceBreakPointForAlpha ~ pphForagingResourceForAlpha)
summary(pphParasiteVirulenceLM)
  #breakPoint = -4.67727 + pphForaging*4.84545
  #df = 1, 9
  #p = 2.139*10^(-15)
  #adj R^2 = 0.9992

pphMuPositiveLM <- lm(pphResourceBreakPointForMuPositive ~ pphForagingResourceForMuPositive)
summary(pphMuPositiveLM)
  #breakPoint = -0.916734 + pphForaging*2.060081
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9997

pphLambdaLM <- lm(pphResourceBreakPointForLambda ~ pphForagingResourceForLambda)
summary(pphLambdaLM)
  #breakPoint = -1.30202 + pphForaging*1.70565
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9963

pphMuNegativeLM <- lm(pphResourceBreakPointForMuNegative ~ pphForagingResourceForMuNegative)
summary(pphMuNegativeLM)
  #breakPoint = -0.916734 + pphForaging*2.060081
  #df = 1, 29
  #p = 2.2*10^(-16)
  #adj R^2 = 0.9997

```

```{r - Linear Regression Predicted Points - Creating vectors that have the line of best fit points (when paired with foragingResource)}
hostBirthLMPoints <- c()
hostDeathLMPoints <- c()
hostCarryingCapacityLMPoints <- c()
hostParasiteVirulenceLMPoints <- c()
hostMuPositiveLMPoints <- c()
hostLambdaLMPoints <- c()
hostMuNegativeLMPoints <- c()

hostBirthLMPointsPair <- c()
hostDeathLMPointsPair <- c()
hostCarryingCapacityLMPointsPair <- c()
hostParasiteVirulenceLMPointsPair <- c()
hostMuPositiveLMPointsPair <- c()
hostLambdaLMPointsPair <- c()
hostMuNegativeLMPointsPair <- c()

pphBirthLMPoints <- c()
pphDeathLMPoints <- c()
pphCarryingCapacityLMPoints <- c()
pphParasiteVirulenceLMPoints <- c()
pphMuPositiveLMPoints <- c()
pphLambdaLMPoints <- c()
pphMuNegativeLMPoints <- c()

pphBirthLMPointsPair <- c()
pphDeathLMPointsPair <- c()
pphCarryingCapacityLMPointsPair <- c()
pphParasiteVirulenceLMPointsPair <- c()
pphMuPositiveLMPointsPair <- c()
pphLambdaLMPointsPair <- c()
pphMuNegativeLMPointsPair <- c()

#Calculating Regression line points (line of best fit points)
for (j in 1:length(foragingResource)){
  tempHostBirthLMPoints = unname((hostBirthLM$coefficients[1] + hostBirthLM$coefficients[2]*foragingResource[j])) #unname() removes the Intercept and Slope terms added by lm()
  hostBirthLMPoints <- append(hostBirthLMPoints, values=tempHostBirthLMPoints)
  hostBirthLMPointsPair <- append(hostBirthLMPointsPair, values=foragingResource[j])
  
  tempHostDeathLMPoints = unname((hostDeathLM$coefficients[1] + hostDeathLM$coefficients[2]*foragingResource[j]))
  hostDeathLMPoints <- append(hostDeathLMPoints, values=tempHostDeathLMPoints)
  hostDeathLMPointsPair <- append(hostDeathLMPointsPair, values=foragingResource[j])
  
  tempHostCarryingCapacityLMPoints = unname((hostCarryingCapacityLM$coefficients[1] + hostCarryingCapacityLM$coefficients[2]*foragingResource[j])) 
  hostCarryingCapacityLMPoints <- append(hostCarryingCapacityLMPoints, values=tempHostCarryingCapacityLMPoints)
  hostCarryingCapacityLMPointsPair <- append(hostCarryingCapacityLMPointsPair, values=foragingResource[j])
  
  #tempHostParasiteVirulenceLMPoints = unname((HostParasiteVirulenceLM$coefficients[1] + HostParasiteVirulenceLM$coefficients[2]*foragingResource[j])) #DOESNT WORK ONLY 1 PT
  #hostParasiteVirulenceLMPoints <- append(hostParasiteVirulenceLMPoints, values=tempHostParasiteVirulenceLMPoints)
  #hostParasiteVirulenceLMPointsPair <- append(hostParasiteVirulenceLMPointsPair, values=foragingResource[j])

  tempHostMuPositiveLMPoints = unname((hostMuPositiveLM$coefficients[1] + hostMuPositiveLM$coefficients[2]*foragingResource[j])) 
  hostMuPositiveLMPoints <- append(hostMuPositiveLMPoints, values=tempHostMuPositiveLMPoints)
  hostMuPositiveLMPointsPair <- append(hostMuPositiveLMPointsPair, values=foragingResource[j])

  tempHostLambdaLMPoints = unname((hostLambdaLM$coefficients[1] + hostLambdaLM$coefficients[2]*foragingResource[j]))
  hostLambdaLMPoints <- append(hostLambdaLMPoints, values=tempHostLambdaLMPoints)
  hostLambdaLMPointsPair <- append(hostLambdaLMPointsPair, values=foragingResource[j])

  tempHostMuNegativeLMPoints = unname((hostMuNegativeLM$coefficients[1] + hostMuNegativeLM$coefficients[2]*foragingResource[j])) 
  hostMuNegativeLMPoints <- append(hostMuNegativeLMPoints, values=tempHostMuNegativeLMPoints)
  hostMuNegativeLMPointsPair <- append(hostMuNegativeLMPointsPair, values=foragingResource[j])

  ##################################################################################################################################################################
  
  tempPphBirthLMPoints = unname((pphBirthLM$coefficients[1] + pphBirthLM$coefficients[2]*foragingResource[j])) #unname() removes the Intercept and Slope terms added by lm()
  pphBirthLMPoints <- append(pphBirthLMPoints, values=tempPphBirthLMPoints)
  pphBirthLMPointsPair <- append(pphBirthLMPointsPair, values=foragingResource[j])
  
  tempPphDeathLMPoints = unname((pphDeathLM$coefficients[1] + pphDeathLM$coefficients[2]*foragingResource[j]))
  pphDeathLMPoints <- append(pphDeathLMPoints, values=tempPphDeathLMPoints)
  pphDeathLMPointsPair <- append(pphDeathLMPointsPair, values=foragingResource[j])
  
  tempPphCarryingCapacityLMPoints = unname((pphCarryingCapacityLM$coefficients[1] + pphCarryingCapacityLM$coefficients[2]*foragingResource[j])) 
  pphCarryingCapacityLMPoints <- append(pphCarryingCapacityLMPoints, values=tempPphCarryingCapacityLMPoints)
  pphCarryingCapacityLMPointsPair <- append(pphCarryingCapacityLMPointsPair, values=foragingResource[j])

  tempPphParasiteVirulenceLMPoints = unname((pphParasiteVirulenceLM$coefficients[1] + pphParasiteVirulenceLM$coefficients[2]*foragingResource[j])) 
  pphParasiteVirulenceLMPoints <- append(pphParasiteVirulenceLMPoints, values=tempPphParasiteVirulenceLMPoints)
  pphParasiteVirulenceLMPointsPair <- append(pphParasiteVirulenceLMPointsPair, values=foragingResource[j])

  tempPphMuPositiveLMPoints = unname((pphMuPositiveLM$coefficients[1] + pphMuPositiveLM$coefficients[2]*foragingResource[j])) 
  pphMuPositiveLMPoints <- append(pphMuPositiveLMPoints, values=tempPphMuPositiveLMPoints)
  pphMuPositiveLMPointsPair <- append(pphMuPositiveLMPointsPair, values=foragingResource[j])

  tempPphLambdaLMPoints = unname((pphLambdaLM$coefficients[1] + pphLambdaLM$coefficients[2]*foragingResource[j]))
  pphLambdaLMPoints <- append(pphLambdaLMPoints, values=tempPphLambdaLMPoints)
  pphLambdaLMPointsPair <- append(pphLambdaLMPointsPair, values=foragingResource[j])

  tempPphMuNegativeLMPoints = unname((pphMuNegativeLM$coefficients[1] + pphMuNegativeLM$coefficients[2]*foragingResource[j])) 
  pphMuNegativeLMPoints <- append(pphMuNegativeLMPoints, values=tempPphMuNegativeLMPoints)
  pphMuNegativeLMPointsPair <- append(pphMuNegativeLMPointsPair, values=foragingResource[j])

}

#Saving the ENDING POINT of line of best fit so that we can graph the symbols larger later
#using linear regression equation to create a point of resourceBreakpoint that we can put in the graph to show which line is for which nonForagingParameter
hostBirthLMEndPoint = max(hostBirthLMPoints[hostBirthLMPoints <= max(resource)])
hostDeathLMEndPoint = max(hostDeathLMPoints[hostDeathLMPoints <= max(resource)])
hostCarryingCapacityLMEndPoint = max(hostCarryingCapacityLMPoints[hostCarryingCapacityLMPoints <= max(resource)])
#hostParasiteVirulenceLMEndPoint = max(hostParasiteVirulenceLMPoints[hostParasiteVirulenceLMPoints <= max(resource)]) #Doesn't work since only 1 point
hostMuPositiveLMEndPoint = max(hostMuPositiveLMPoints[hostMuPositiveLMPoints <= max(resource)])
hostLambdaLMEndPoint = max(hostLambdaLMPoints[hostLambdaLMPoints <= max(resource)])
hostMuNegativeLMEndPoint = max(hostMuNegativeLMPoints[hostMuNegativeLMPoints <= max(resource)])

hostBirthLMEndPointPair = hostBirthLMPointsPair[length(hostBirthLMPoints[hostBirthLMPoints <= max(resource)])]
hostDeathLMEndPointPair = hostDeathLMPointsPair[length(hostDeathLMPoints[hostDeathLMPoints <= max(resource)])]
hostCarryingCapacityLMEndPointPair = hostCarryingCapacityLMPointsPair[length(hostCarryingCapacityLMPoints[hostCarryingCapacityLMPoints <= max(resource)])]
#hostParasiteVirulenceLMEndPointPair = hostParasiteVirulenceLMPointsPair[length(hostParasiteVirulenceLMPoints[hostParasiteVirulenceLMPoints <= max(resource)])]
hostMuPositiveLMEndPointPair = hostMuPositiveLMPointsPair[length(hostMuPositiveLMPoints[hostMuPositiveLMPoints <= max(resource)])]
hostLambdaLMEndPointPair = hostLambdaLMPointsPair[length(hostLambdaLMPoints[hostLambdaLMPoints <= max(resource)])]
hostMuNegativeLMEndPointPair = hostMuNegativeLMPointsPair[length(hostMuNegativeLMPoints[hostMuNegativeLMPoints <= max(resource)])]

pphBirthLMEndPoint = max(pphBirthLMPoints[pphBirthLMPoints <= max(resource)])
pphDeathLMEndPoint = max(pphDeathLMPoints[pphDeathLMPoints <= max(resource)])
pphCarryingCapacityLMEndPoint = max(pphCarryingCapacityLMPoints[pphCarryingCapacityLMPoints <= max(resource)])
pphParasiteVirulenceLMEndPoint = max(pphParasiteVirulenceLMPoints[pphParasiteVirulenceLMPoints <= max(resource)])
pphMuPositiveLMEndPoint = max(pphMuPositiveLMPoints[pphMuPositiveLMPoints <= max(resource)])
pphLambdaLMEndPoint = max(pphLambdaLMPoints[pphLambdaLMPoints <= max(resource)])
pphMuNegativeLMEndPoint = max(pphMuNegativeLMPoints[pphMuNegativeLMPoints <= max(resource)])

pphBirthLMEndPointPair = pphBirthLMPointsPair[length(pphBirthLMPoints[pphBirthLMPoints <= max(resource)])]
pphDeathLMEndPointPair = pphDeathLMPointsPair[length(pphDeathLMPoints[pphDeathLMPoints <= max(resource)])]
pphCarryingCapacityLMEndPointPair = pphCarryingCapacityLMPointsPair[length(pphCarryingCapacityLMPoints[pphCarryingCapacityLMPoints <= max(resource)])]
pphParasiteVirulenceLMEndPointPair = pphParasiteVirulenceLMPointsPair[length(pphParasiteVirulenceLMPoints[pphParasiteVirulenceLMPoints <= max(resource)])]
pphMuPositiveLMEndPointPair = pphMuPositiveLMPointsPair[length(pphMuPositiveLMPoints[pphMuPositiveLMPoints <= max(resource)])]
pphLambdaLMEndPointPair = pphLambdaLMPointsPair[length(pphLambdaLMPoints[pphLambdaLMPoints <= max(resource)])]
pphMuNegativeLMEndPointPair = pphMuNegativeLMPointsPair[length(pphMuNegativeLMPoints[pphMuNegativeLMPoints <= max(resource)])]

```

```{r - Creating datasets}
#Ranked by nonForagingParameter alphabetization (because we graph our values by NFP for legend)
bShape <- 0
dShape <- 2
KcarryCapShape <- 1
AlphaShape <- 6
MuPositiveShape <- 5
LambdaShape <- 3
MuNegativeShape <- 4

#Creating dataframes for hosts and pph intensity
#Dataframe variables are resourceBreakPoints, foragingResourceLevel, nonForagingParameter, NNP, and pointShape
  #resourceBreakPoints = amount of resource subsidy required for the nonforaging parameter to flip the effect of foraging parameters beta & k
  #foragingResourceLevel = amount of resource subsidy that the foraging parameters experience when the flip occurs
  #nonForagingParameter = name of foraging parameter (used for graphing shapes and legend)
  #NNP = names of direction of resource effect on foraging parameters (used for graphing lines)
  #pointShape = assigned value from above (used for graphing shapes and legend)

hostDataAll <- data.frame(resourceBreakPoints=c(hostResourceBreakPointForB, hostResourceBreakPointForD, hostResourceBreakPointForKcarryCap, hostResourceBreakPointForAlpha, hostResourceBreakPointForMuPositive, hostResourceBreakPointForLambda, hostResourceBreakPointForMuNegative),
                          foragingResourceLevel=c(hostForagingResourceForB, hostForagingResourceForD, hostForagingResourceForKcarryCap, hostForagingResourceForAlpha, hostForagingResourceForMuPositive, hostForagingResourceForLambda, hostForagingResourceForMuNegative), 
                          nonForagingParameter=c(rep("Host Birth Rate", times=length(hostResourceBreakPointForB)), rep("Host Natural Mortality", times=length(hostResourceBreakPointForD)), rep("Host Carrying Capacity", times=length(hostResourceBreakPointForKcarryCap)), rep("Parasite Virulence", times=length(hostResourceBreakPointForAlpha)), rep("Parasite Mortality+", times=length(hostResourceBreakPointForMuPositive)), rep("Parasite Egg Production", times=length(hostResourceBreakPointForLambda)), rep("Parasite Mortality-", times=length(hostResourceBreakPointForMuNegative))),
                          NNP=c(rep("Increased Host Overlap", times=length(hostResourceBreakPointForB)), rep("Decreased Host Overlap", times=length(hostResourceBreakPointForD)), rep("Increased Host Overlap", times=length(hostResourceBreakPointForKcarryCap)), rep("Decreased Host Overlap", times=length(hostResourceBreakPointForAlpha)), rep("Increased Host Overlap", times=length(hostResourceBreakPointForMuPositive)), rep("Decreased Host Overlap", times=length(hostResourceBreakPointForLambda)), rep("Decreased Host Overlap", times=length(hostResourceBreakPointForMuNegative))),
                          pointShape=c(rep(bShape, times=length(hostResourceBreakPointForB)), rep(dShape, times=length(hostResourceBreakPointForD)), rep(KcarryCapShape, times=length(hostResourceBreakPointForKcarryCap)), rep(AlphaShape, times=length(hostResourceBreakPointForAlpha)), rep(MuPositiveShape, times=length(hostResourceBreakPointForMuPositive)), rep(LambdaShape, times=length(hostResourceBreakPointForLambda)), rep(MuNegativeShape, times=length(hostResourceBreakPointForMuNegative)))
                       )

pphDataAll <- data.frame(resourceBreakPoints=c(pphResourceBreakPointForB, pphResourceBreakPointForD, pphResourceBreakPointForKcarryCap, pphResourceBreakPointForAlpha, pphResourceBreakPointForMuPositive, pphResourceBreakPointForLambda, pphResourceBreakPointForMuNegative),
                       foragingResourceLevel=c(pphForagingResourceForB, pphForagingResourceForD, pphForagingResourceForKcarryCap, pphForagingResourceForAlpha, pphForagingResourceForMuPositive, pphForagingResourceForLambda, pphForagingResourceForMuNegative),
                       nonForagingParameter=c(rep("Host Birth Rate", times=length(pphResourceBreakPointForB)), rep("Host Natural Mortality", times=length(pphResourceBreakPointForD)), rep("Host Carrying Capacity", times=length(pphResourceBreakPointForKcarryCap)), rep("Parasite Virulence", times=length(pphResourceBreakPointForAlpha)), rep("Parasite Mortality+", times=length(pphResourceBreakPointForMuPositive)), rep("Parasite Egg Production", times=length(pphResourceBreakPointForLambda)), rep("Parasite Mortality-", times=length(pphResourceBreakPointForMuNegative))),
                       NNP=c(rep("Decreased Host Overlap", times=length(pphResourceBreakPointForB)), rep("Decreased Host Overlap", times=length(pphResourceBreakPointForD)), rep("Decreased Host Overlap", times=length(pphResourceBreakPointForKcarryCap)), rep("Decreased Host Overlap", times=length(pphResourceBreakPointForAlpha)), rep("Increased Host Overlap", times=length(pphResourceBreakPointForMuPositive)), rep("Decreased Host Overlap", times=length(pphResourceBreakPointForLambda)), rep("Decreased Host Overlap", times=length(pphResourceBreakPointForMuNegative))),
                       pointShape=c(rep(bShape, times=length(pphResourceBreakPointForB)), rep(dShape, times=length(pphResourceBreakPointForD)), rep(KcarryCapShape, times=length(pphResourceBreakPointForKcarryCap)), rep(AlphaShape, times=length(pphResourceBreakPointForAlpha)), rep(MuPositiveShape, times=length(pphResourceBreakPointForMuPositive)), rep(LambdaShape, times=length(pphResourceBreakPointForLambda)), rep(MuNegativeShape, times=length(pphResourceBreakPointForMuNegative)))
                       )

#Creating dataframes for Regression Predictions of hosts and pph intensity
#Dataframe variables are resourceBreakPoints, foragingResourceLevel, nonForagingParameter, NNP, and pointShape
  #predictedLMPoints = predicted amount of resource subsidy required for the nonforaging parameter to flip the effect of foraging parameters beta & k
  #pairedForagingResourcePoints = predicted amount of resource subsidy that the foraging parameters experience when the flip occurs
  #nonForagingParameter = name of foraging parameter (used for graphing shapes and legend)
  #NNP = names of direction of resource effect on foraging parameters (used for graphing lines)
  #pointShape = assigned value from above (used for graphing shapes and legend)

hostRegressionData <- data.frame(predictedLMPoints=c(hostBirthLMPoints, hostDeathLMPoints, hostCarryingCapacityLMPoints, hostMuPositiveLMPoints, hostLambdaLMPoints, hostMuNegativeLMPoints),
                                 pairedForagingResourcePoints=c(hostBirthLMPointsPair, hostDeathLMPointsPair, hostCarryingCapacityLMPointsPair, hostMuPositiveLMPointsPair, hostLambdaLMPointsPair, hostMuNegativeLMPointsPair),
                                 NNP=c(rep("Increased Host Overlap", times=length(hostBirthLMPoints)), rep("Decreased Host Overlap", times=length(hostDeathLMPoints)), rep("Increased Host Overlap", times=length(hostCarryingCapacityLMPoints)), rep("Increased Host Overlap", times=length(hostMuPositiveLMPoints)), rep("Decreased Host Overlap", times=length(hostLambdaLMPoints)), rep("Decreased Host Overlap", times=length(hostMuNegativeLMPoints))),
                                 nonForagingParameter=c(rep("Host Birth Rate", times=length(hostBirthLMPoints)), rep("Host Natural Mortality", times=length(hostDeathLMPoints)), rep("Host Carrying Capacity", times=length(hostCarryingCapacityLMPoints)), rep("Parasite Mortality+", times=length(hostMuPositiveLMPoints)), rep("Parasite Egg Production", times=length(hostLambdaLMPoints)), rep("Parasite Mortality-", times=length(hostMuNegativeLMPoints))),
                                 pointShape=c(rep(bShape, times=length(hostBirthLMPoints)), rep(dShape, times=length(hostDeathLMPoints)), rep(KcarryCapShape, times=length(hostCarryingCapacityLMPoints)), rep(MuPositiveShape, times=length(hostMuPositiveLMPoints)), rep(LambdaShape, times=length(hostLambdaLMPoints)), rep(MuNegativeShape, times=length(hostMuNegativeLMPoints)))
                                 )

pphRegressionData <- data.frame(predictedLMPoints=c(pphBirthLMPoints, pphDeathLMPoints, pphCarryingCapacityLMPoints, pphParasiteVirulenceLMPoints, pphMuPositiveLMPoints, pphLambdaLMPoints, pphMuNegativeLMPoints),
                                 pairedForagingResourcePoints=c(pphBirthLMPointsPair, pphDeathLMPointsPair, pphCarryingCapacityLMPointsPair, pphParasiteVirulenceLMPointsPair, pphMuPositiveLMPointsPair, pphLambdaLMPointsPair, pphMuNegativeLMPointsPair),
                                NNP=c(rep("Decreased Host Overlap", times=length(pphBirthLMPoints)), rep("Decreased Host Overlap", times=length(pphDeathLMPoints)), rep("Decreased Host Overlap", times=length(pphCarryingCapacityLMPoints)), rep("Decreased Host Overlap", times=length(pphParasiteVirulenceLMPoints)), rep("Increased Host Overlap", times=length(pphMuPositiveLMPoints)), rep("Decreased Host Overlap", times=length(pphLambdaLMPoints)), rep("Decreased Host Overlap", times=length(pphMuNegativeLMPoints))),
                                nonForagingParameter=c(rep("Host Birth Rate", times=length(pphBirthLMPoints)), rep("Host Natural Mortality", times=length(pphDeathLMPoints)), rep("Host Carrying Capacity", times=length(pphCarryingCapacityLMPoints)), rep("Parasite Virulence", times=length(pphParasiteVirulenceLMPoints)), rep("Parasite Mortality+", times=length(pphMuPositiveLMPoints)), rep("Parasite Egg Production", times=length(pphLambdaLMPoints)), rep("Parasite Mortality-", times=length(pphMuNegativeLMPoints))),
                                pointShape=c(rep(bShape, times=length(pphBirthLMPoints)), rep(dShape, times=length(pphDeathLMPoints)), rep(KcarryCapShape, times=length(pphCarryingCapacityLMPoints)), rep(AlphaShape, times=length(pphParasiteVirulenceLMPoints)), rep(MuPositiveShape, times=length(pphMuPositiveLMPoints)), rep(LambdaShape, times=length(pphLambdaLMPoints)), rep(MuNegativeShape, times=length(pphMuNegativeLMPoints)))
                                 )

#Creating dataframes for Regression End Points of hosts and pph intensity
#Dataframe variables are resourceBreakPoints, foragingResourceLevel, nonForagingParameter, NNP, and pointShape
  #predictedNonForagingEndPoints = predicted amount of resource subsidy required for the nonforaging parameter to flip the effect of foraging parameters beta & k
  #pairedForagingEndPoints = predicted amount of resource subsidy that the foraging parameters experience when the flip occurs
  #nonForagingParameter = name of foraging parameter (used for graphing shapes and legend)
  #NNP = names of direction of resource effect on foraging parameters (used for graphing lines)
  #pointShape = assigned value from above (used for graphing shapes and legend)

hostRegressionEndPoints <- data.frame(predictedNonForagingEndPoints=c(hostBirthLMEndPoint, hostDeathLMEndPoint, hostCarryingCapacityLMEndPoint, hostMuPositiveLMEndPoint, hostLambdaLMEndPoint, hostMuNegativeLMEndPoint), #NONFORAGING RESOURCES (y-axis)
                                      pairedForagingEndPoints=c(hostBirthLMEndPointPair, hostDeathLMEndPointPair, hostCarryingCapacityLMEndPointPair, hostMuPositiveLMEndPointPair, hostLambdaLMEndPointPair, hostMuNegativeLMEndPointPair), #FORAGING RESOURCES (x-axis)
                                      nonForagingParameter=c("Host Birth Rate", "Host Natural Mortality", "Host Carrying Capacity", "Parasite Mortality+", "Parasite Egg Production", "Parasite Mortality-"),
                                      NNP=c("Increased Host Overlap", "Decreased Host Overlap", "Increased Host Overlap",  "Increased Host Overlap", "Decreased Host Overlap", "Decreased Host Overlap"),
                                      pointShape=c(bShape, dShape, KcarryCapShape, MuPositiveShape, LambdaShape, MuNegativeShape)
                                      )

pphRegressionEndPoints <- data.frame(predictedNonForagingEndPoints=c(pphBirthLMEndPoint, pphDeathLMEndPoint, pphCarryingCapacityLMEndPoint, pphParasiteVirulenceLMEndPoint, pphMuPositiveLMEndPoint, pphLambdaLMEndPoint, pphMuNegativeLMEndPoint), #NONFORAGING RESOURCES (y-axis)
                                      pairedForagingEndPoints=c(pphBirthLMEndPointPair, pphDeathLMEndPointPair, pphCarryingCapacityLMEndPointPair, pphParasiteVirulenceLMEndPointPair, pphMuPositiveLMEndPointPair, pphLambdaLMEndPointPair, pphMuNegativeLMEndPointPair), #FORAGING RESOURCES (x-axis)
                                      nonForagingParameter=c("Host Birth Rate", "Host Natural Mortality", "Host Carrying Capacity", "Parasite Virulence", "Parasite Mortality+", "Parasite Egg Production", "Parasite Mortality-"),
                                     NNP=c("Decreased Host Overlap", "Decreased Host Overlap", "Decreased Host Overlap", "Decreased Host Overlap", "Increased Host Overlap", "Decreased Host Overlap", "Decreased Host Overlap"),
                                     pointShape=c(bShape, dShape, KcarryCapShape, AlphaShape, MuPositiveShape, LambdaShape, MuNegativeShape)
                                     ) 

#Subsetting our data to graph 2x2 panels
hostDataPositive <- subset.data.frame(hostDataAll, NNP=="Increased Host Overlap", select=TRUE)
hostDataPositiveB <- subset.data.frame(hostDataAll, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
hostDataPositiveCarryingCapacity <- subset.data.frame(hostDataAll, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
hostDataPositiveParasiteMortalityPositive <- subset.data.frame(hostDataAll, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

hostDataNegative <- subset.data.frame(hostDataAll, NNP=="Decreased Host Overlap", select=TRUE)
hostDataNegativeD <- subset.data.frame(hostDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
hostDataNegativeEggProduction <- subset.data.frame(hostDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
hostDataNegativeParasiteMortalityNegative <- subset.data.frame(hostDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

pphDataPositive <- subset.data.frame(pphDataAll, NNP=="Increased Host Overlap", select=TRUE)
pphDataPositiveParasiteMortalityPositive <- subset.data.frame(pphDataAll, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

pphDataNegative <- subset.data.frame(pphDataAll, NNP=="Decreased Host Overlap", select=TRUE)
pphDataNegativeB <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
pphDataNegativeD <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
pphDataNegativeCarryingCapacity <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
pphDataNegativeParasiteVirulence <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Virulence"), select=TRUE)
pphDataNegativeEggProduction <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
pphDataNegativeParasiteMortalityNegative <- subset.data.frame(pphDataAll, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

hostRegressionDataPositive <- subset.data.frame(hostRegressionData, NNP=="Increased Host Overlap", select=TRUE)
hostRegressionDataPositiveB <- subset.data.frame(hostRegressionData, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
hostRegressionDataPositiveCarryingCapacity <- subset.data.frame(hostRegressionData, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
hostRegressionDataPositiveParasiteMortalityPositive <- subset.data.frame(hostRegressionData, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

hostRegressionDataNegative <- subset.data.frame(hostRegressionData, NNP=="Decreased Host Overlap", select=TRUE)
hostRegressionDataNegativeD <- subset.data.frame(hostRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
hostRegressionDataNegativeEggProduction <- subset.data.frame(hostRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
hostRegressionDataNegativeParasiteMortalityNegative <- subset.data.frame(hostRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

pphRegressionDataPositive <- subset.data.frame(pphRegressionData, NNP=="Increased Host Overlap", select=TRUE)
pphRegressionDataPositiveParasiteMortalityPositive <- subset.data.frame(pphRegressionData, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

pphRegressionDataNegative <- subset.data.frame(pphRegressionData, NNP=="Decreased Host Overlap", select=TRUE)
pphRegressionDataNegativeB <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
pphRegressionDataNegativeD <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
pphRegressionDataNegativeCarryingCapacity <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
pphRegressionDataNegativeParasiteVirulence <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Virulence"), select=TRUE)
pphRegressionDataNegativeEggProduction <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
pphRegressionDataNegativeParasiteMortalityNegative <- subset.data.frame(pphRegressionData, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

hostRegressionEndPointsPositive <- subset.data.frame(hostRegressionEndPoints, NNP=="Increased Host Overlap", select=TRUE)
hostRegressionEndPointsPositiveB <- subset.data.frame(hostRegressionEndPoints, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
hostRegressionEndPointsPositiveCarryingCapacity <- subset.data.frame(hostRegressionEndPoints, (NNP=="Increased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
hostRegressionEndPointsPositiveParasiteMortalityPositive <- subset.data.frame(hostRegressionEndPoints, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

hostRegressionEndPointsNegative <- subset.data.frame(hostRegressionEndPoints, NNP=="Decreased Host Overlap", select=TRUE)
hostRegressionEndPointsNegativeD <- subset.data.frame(hostRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
hostRegressionEndPointsNegativeEggProduction <- subset.data.frame(hostRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
hostRegressionEndPointsNegativeParasiteMortalityNegative <- subset.data.frame(hostRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

pphRegressionEndPointsPositive <- subset.data.frame(pphRegressionEndPoints, NNP=="Increased Host Overlap", select=TRUE)
pphRegressionEndPointsPositiveParasiteMortalityPositive <- subset.data.frame(pphRegressionEndPoints, (NNP=="Increased Host Overlap" & nonForagingParameter=="Parasite Mortality+"), select=TRUE)

pphRegressionEndPointsNegative <- subset.data.frame(pphRegressionEndPoints, NNP=="Decreased Host Overlap", select=TRUE)
pphRegressionEndPointsNegativeB <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Birth Rate"), select=TRUE)
pphRegressionEndPointsNegativeD <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Natural Mortality"), select=TRUE)
pphRegressionEndPointsNegativeCarryingCapacity <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Host Carrying Capacity"), select=TRUE)
pphRegressionEndPointsNegativeParasiteVirulence <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Virulence"), select=TRUE)
pphRegressionEndPointsNegativeEggProduction <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Egg Production"), select=TRUE)
pphRegressionEndPointsNegativeParasiteMortalityNegative <- subset.data.frame(pphRegressionEndPoints, (NNP=="Decreased Host Overlap" & nonForagingParameter=="Parasite Mortality-"), select=TRUE)

#Creating dataset for legend
legendDataframe <- data.frame(xValue=c(1, 2, 3, 4, 5, 6, 7),
                              yValue=c(1, 2, 3, 4, 5, 6, 7),
                              nonForagingParameter=c("Host Birth Rate", "Host Natural Mortality", "Host Carrying Capacity", "Parasite Virulence", "Parasite Mortality+", "Parasite Egg Production", "Parasite Mortality-"),
                              NNP=c("Decreased Host Overlap", "Increased Host Overlap", "Decreased Host Overlap", "Decreased Host Overlap", "Increased Host Overlap", "Increased Host Overlap", "Increased Host Overlap"),
                              pointShape=c(bShape, dShape, KcarryCapShape, AlphaShape, MuPositiveShape, LambdaShape, MuNegativeShape)
                              )

```

```{r - Graphing - Plot foragingResource along x-axis, breakpoints along y-axis, colored/marked by parameter and NNP type}
hostBreakpointsNegative <- ggplot() +
  #Regression lines
  geom_line(data=hostRegressionDataNegativeD, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=hostRegressionDataNegativeEggProduction, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=hostRegressionDataNegativeParasiteMortalityNegative, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  #Model outputs as points
  geom_point(data=hostDataNegativeD, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataNegativeD$pointShape, size=1.2) + 
  geom_point(data=hostDataNegativeEggProduction, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataNegativeEggProduction$pointShape, size=1.2) + 
  geom_point(data=hostDataNegativeParasiteMortalityNegative, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataNegativeParasiteMortalityNegative$pointShape, size=1.2) + 
  #Regression line "end points" to match model output
  geom_point(data=hostRegressionEndPointsNegativeD, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsNegativeD$pointShape, size=3) +
  geom_point(data=hostRegressionEndPointsNegativeEggProduction, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsNegativeEggProduction$pointShape, size=3) + 
  geom_point(data=hostRegressionEndPointsNegativeParasiteMortalityNegative, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsNegativeParasiteMortalityNegative$pointShape, size=3) + 
  #Resource effect 1:1 line for interpretation
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  #Legend Stuff
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +            #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                            #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")), y = expression(bold("Host Resource Breakpoint"))) +
  #guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  #guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  #guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points
  theme_bw() #+
  #theme(legend.position = "none")

hostBreakpointsPositive <- ggplot() +
  #Regression lines
  geom_line(data=hostRegressionDataPositiveB, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightblue", size=1.2) + 
  geom_line(data=hostRegressionDataPositiveCarryingCapacity, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightblue", size=1.2) + 
  geom_line(data=hostRegressionDataPositiveParasiteMortalityPositive, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightblue", size=1.2) + 
  #Model outputs as points
  geom_point(data=hostDataPositiveB, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataPositiveB$pointShape, size=1.2) + 
  geom_point(data=hostDataPositiveCarryingCapacity, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataPositiveCarryingCapacity$pointShape, size=1.2) + 
  geom_point(data=hostDataPositiveParasiteMortalityPositive, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=hostDataPositiveParasiteMortalityPositive$pointShape, size=1.2) + 
  #Regression line "end points" to match model output
  geom_point(data=hostRegressionEndPointsPositiveB, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsPositiveB$pointShape, size=3) +
  geom_point(data=hostRegressionEndPointsPositiveCarryingCapacity, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsPositiveCarryingCapacity$pointShape, size=3) + 
  geom_point(data=hostRegressionEndPointsPositiveParasiteMortalityPositive, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=hostRegressionEndPointsPositiveParasiteMortalityPositive$pointShape, size=3) + 
  #Resource effect 1:1 line for interpretation
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  #Legend Stuff
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +            #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                            #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")), y = expression(bold("Host Resource Breakpoint"))) +
  #guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  #guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  #guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points
  theme_bw() #+
  #theme(legend.position = "none")

pphBreakpointsNegative <- ggplot() +
  #Regression lines
  geom_line(data=pphRegressionDataNegativeB, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=pphRegressionDataNegativeD, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=pphRegressionDataNegativeCarryingCapacity, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) +
  geom_line(data=pphRegressionDataNegativeParasiteVirulence, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=pphRegressionDataNegativeEggProduction, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  geom_line(data=pphRegressionDataNegativeParasiteMortalityNegative, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightcoral", size=1.2) + 
  #Model outputs as points
  geom_point(data=pphDataNegativeB, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeB$pointShape, size=1.2) + 
  geom_point(data=pphDataNegativeD, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeD$pointShape, size=1.2) + 
  geom_point(data=pphDataNegativeCarryingCapacity, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeCarryingCapacity$pointShape, size=1.2) +  
  geom_point(data=pphDataNegativeParasiteVirulence, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeParasiteVirulence$pointShape, size=1.2) + 
  geom_point(data=pphDataNegativeEggProduction, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeEggProduction$pointShape, size=1.2) + 
  geom_point(data=pphDataNegativeParasiteMortalityNegative, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataNegativeParasiteMortalityNegative$pointShape, size=1.2) + 
  #Regression line "end points" to match model output
  geom_point(data=pphRegressionEndPointsNegativeB, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeB$pointShape, size=3) +
  geom_point(data=pphRegressionEndPointsNegativeD, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeD$pointShape, size=3) + 
  geom_point(data=pphRegressionEndPointsNegativeCarryingCapacity, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeCarryingCapacity$pointShape, size=3) +   
  geom_point(data=pphRegressionEndPointsNegativeParasiteVirulence, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeParasiteVirulence$pointShape, size=3) +
  geom_point(data=pphRegressionEndPointsNegativeEggProduction, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeEggProduction$pointShape, size=3) + 
  geom_point(data=pphRegressionEndPointsNegativeParasiteMortalityNegative, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsNegativeParasiteMortalityNegative$pointShape, size=3) + 
  #Resource effect 1:1 line for interpretation
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  #Legend Stuff
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +            #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                            #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")), y = expression(bold("Pph Resource Breakpoint"))) +
  #guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  #guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  #guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points
  theme_bw() #+
  #theme(legend.position = "none")

pphBreakpointsPositive <- ggplot() +
  #Regression lines
  geom_line(data=pphRegressionDataPositiveParasiteMortalityPositive, aes(x=pairedForagingResourcePoints, y=predictedLMPoints), color="lightblue", size=1.2) + 
  #Model outputs as points
    geom_point(data=pphDataPositiveParasiteMortalityPositive, aes(x=foragingResourceLevel, y=resourceBreakPoints), shape=pphDataPositiveParasiteMortalityPositive$pointShape, size=1.2) + 
  #Regression line "end points" to match model output
    geom_point(data=pphRegressionEndPointsPositiveParasiteMortalityPositive, aes(x=pairedForagingEndPoints, y=predictedNonForagingEndPoints), shape=pphRegressionEndPointsPositiveParasiteMortalityPositive$pointShape, size=3) + 
  #Resource effect 1:1 line for interpretation
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  #Legend Stuff
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +                      #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                                      #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")), y = expression(bold("Pph Resource Breakpoint"))) +
  #guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  #guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  #guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points  
  theme_bw() #+
  #theme(legend.position = "none")

fakeGraphForLegend <- ggplot() +
  geom_line(data=legendDataframe, aes(x=xValue, y=yValue, group=nonForagingParameter, color=NNP), size=1.2) +        
  geom_point(data=legendDataframe, aes(x=xValue, y=yValue, shape=nonForagingParameter), size=3) +  #, position=position_dodge(width=0.05)
  scale_shape_manual(values=c(bShape, KcarryCapShape, dShape, LambdaShape, MuNegativeShape, MuPositiveShape, AlphaShape)) + #THIS IS BAD PRACTICE! Breaks graph, but fixes legend which is all we care about in this fake graph
  labs(x = expression(bold("Fake Graph X Axis")), y = expression(bold("Fake Graph Y Axis"))) +
  guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  guides(shape = guide_legend(title="Non-Foraging Parameters")) #Changes title of legend for shape of points  

legendGraph <- cowplot::get_legend(fakeGraphForLegend)

#Visualization choices
plot_grid(hostBreakpointsNegative, hostBreakpointsPositive, legendGraph, pphBreakpointsNegative, pphBreakpointsPositive, ncol=3, nrow=2)
plot_grid(hostBreakpointsNegative, legendGraph, hostBreakpointsPositive, ncol=2, nrow=2)
plot_grid(pphBreakpointsNegative, legendGraph, pphBreakpointsPositive, ncol=2, nrow=2)
```


################################################################################################################### 
#This portion needs to be run 4 times (each time change the ForagingResource value)

```{r - Finding Minimum and Maximum Values for each combination}
#Hosts
hostMinDiffBNeg <- (min(hostEquilibriumB$H_NegativeB)-hostEquilibriumB$H_NegativeB[1])/hostEquilibriumB$H_NegativeB[1]*100
hostMaxDiffBNeg <- (max(hostEquilibriumB$H_NegativeB)-hostEquilibriumB$H_NegativeB[1])/hostEquilibriumB$H_NegativeB[1]*100

hostMinBNull <- (min(hostEquilibriumB$H_NullB)-hostEquilibriumB$H_NullB[1])/hostEquilibriumB$H_NullB[1]*100
hostMaxBNull <- (max(hostEquilibriumB$H_NullB)-hostEquilibriumB$H_NullB[1])/hostEquilibriumB$H_NullB[1]*100

hostMinBPos <- (min(hostEquilibriumB$H_PositiveB)-hostEquilibriumB$H_PositiveB[1])/hostEquilibriumB$H_PositiveB[1]*100
hostMaxBPos <- (max(hostEquilibriumB$H_PositiveB)-hostEquilibriumB$H_PositiveB[1])/hostEquilibriumB$H_PositiveB[1]*100

hostMinDNeg <- (min(hostEquilibriumD$H_NegativeD)-hostEquilibriumD$H_NegativeD[1])/hostEquilibriumD$H_NegativeD[1]*100
hostMaxDNeg <- (max(hostEquilibriumD$H_NegativeD)-hostEquilibriumD$H_NegativeD[1])/hostEquilibriumD$H_NegativeD[1]*100

hostMinDNull <- (min(hostEquilibriumD$H_NullD)-hostEquilibriumD$H_NullD[1])/hostEquilibriumD$H_NullD[1]*100
hostMaxDNull <- (max(hostEquilibriumD$H_NullD)-hostEquilibriumD$H_NullD[1])/hostEquilibriumD$H_NullD[1]*100

hostMinDPos <- (min(hostEquilibriumD$H_PositiveD)-hostEquilibriumD$H_PositiveD[1])/hostEquilibriumD$H_PositiveD[1]*100
hostMaxDPos <- (max(hostEquilibriumD$H_PositiveD)-hostEquilibriumD$H_PositiveD[1])/hostEquilibriumD$H_PositiveD[1]*100

hostMinKcarryCapNeg <- (min(hostEquilibriumKcarryCap$H_NegativeKcarryCap)-hostEquilibriumKcarryCap$H_NegativeKcarryCap[1])/hostEquilibriumKcarryCap$H_NegativeKcarryCap[1]*100
hostMaxKcarryCapNeg <- (max(hostEquilibriumKcarryCap$H_NegativeKcarryCap)-hostEquilibriumKcarryCap$H_NegativeKcarryCap[1])/hostEquilibriumKcarryCap$H_NegativeKcarryCap[1]*100

hostMinKcarryCapNull <- (min(hostEquilibriumKcarryCap$H_NullKcarryCap)-hostEquilibriumKcarryCap$H_NullKcarryCap[1])/hostEquilibriumKcarryCap$H_NullKcarryCap[1]*100
hostMaxKcarryCapNull <- (max(hostEquilibriumKcarryCap$H_NullKcarryCap)-hostEquilibriumKcarryCap$H_NullKcarryCap[1])/hostEquilibriumKcarryCap$H_NullKcarryCap[1]*100

hostMinKcarryCapPos <- (min(hostEquilibriumKcarryCap$H_PositiveKcarryCap)-hostEquilibriumKcarryCap$H_PositiveKcarryCap[1])/hostEquilibriumKcarryCap$H_PositiveKcarryCap[1]*100
hostMaxKcarryCapPos <- (max(hostEquilibriumKcarryCap$H_PositiveKcarryCap)-hostEquilibriumKcarryCap$H_PositiveKcarryCap[1])/hostEquilibriumKcarryCap$H_PositiveKcarryCap[1]*100

######################################################################################################

#PpH
pphMinBNeg <- (min(pphEquilibriumB$PpH_NegativeB)-pphEquilibriumB$PpH_NegativeB[1])/pphEquilibriumB$PpH_NegativeB[1]*100
pphMaxBNeg <- (max(pphEquilibriumB$PpH_NegativeB)-pphEquilibriumB$PpH_NegativeB[1])/pphEquilibriumB$PpH_NegativeB[1]*100

pphMinBNull <- (min(pphEquilibriumB$PpH_NullB)-pphEquilibriumB$PpH_NullB[1])/pphEquilibriumB$PpH_NullB[1]*100
pphMaxBNull <- (max(pphEquilibriumB$PpH_NullB)-pphEquilibriumB$PpH_NullB[1])/pphEquilibriumB$PpH_NullB[1]*100

pphMinBPos <- (min(pphEquilibriumB$PpH_PositiveB)-pphEquilibriumB$PpH_PositiveB[1])/pphEquilibriumB$PpH_PositiveB[1]*100
pphMaxBPos <- (max(pphEquilibriumB$PpH_PositiveB)-pphEquilibriumB$PpH_PositiveB[1])/pphEquilibriumB$PpH_PositiveB[1]*100

pphMinDNeg <- (min(pphEquilibriumD$PpH_NegativeD)-pphEquilibriumD$PpH_NegativeD[1])/pphEquilibriumD$PpH_NegativeD[1]*100
pphMaxDNeg <- (max(pphEquilibriumD$PpH_NegativeD)-pphEquilibriumD$PpH_NegativeD[1])/pphEquilibriumD$PpH_NegativeD[1]*100

pphMinDNull <- (min(pphEquilibriumD$PpH_NullD)-pphEquilibriumD$PpH_NullD[1])/pphEquilibriumD$PpH_NullD[1]*100
pphMaxDNull <- (max(pphEquilibriumD$PpH_NullD)-pphEquilibriumD$PpH_NullD[1])/pphEquilibriumD$PpH_NullD[1]*100

pphMinDPos <- (min(pphEquilibriumD$PpH_PositiveD)-pphEquilibriumD$PpH_PositiveD[1])/pphEquilibriumD$PpH_PositiveD[1]*100
pphMaxDPos <- (max(pphEquilibriumD$PpH_PositiveD)-pphEquilibriumD$PpH_PositiveD[1])/pphEquilibriumD$PpH_PositiveD[1]*100

pphMinKcarryCapNeg <- (min(pphEquilibriumKcarryCap$PpH_NegativeKcarryCap)-pphEquilibriumKcarryCap$PpH_NegativeKcarryCap[1])/pphEquilibriumKcarryCap$PpH_NegativeKcarryCap[1]*100
pphMaxKcarryCapNeg <- (max(pphEquilibriumKcarryCap$PpH_NegativeKcarryCap)-pphEquilibriumKcarryCap$PpH_NegativeKcarryCap[1])/pphEquilibriumKcarryCap$PpH_NegativeKcarryCap[1]*100

pphMinKcarryCapNull <- (min(pphEquilibriumKcarryCap$PpH_NullKcarryCap)-pphEquilibriumKcarryCap$PpH_NullKcarryCap[1])/pphEquilibriumKcarryCap$PpH_NullKcarryCap[1]*100
pphMaxKcarryCapNull <- (max(pphEquilibriumKcarryCap$PpH_NullKcarryCap)-pphEquilibriumKcarryCap$PpH_NullKcarryCap[1])/pphEquilibriumKcarryCap$PpH_NullKcarryCap[1]*100

pphMinKcarryCapPos <- (min(pphEquilibriumKcarryCap$PpH_PositiveKcarryCap)-pphEquilibriumKcarryCap$PpH_PositiveKcarryCap[1])/pphEquilibriumKcarryCap$PpH_PositiveKcarryCap[1]*100
pphMaxKcarryCapPos <- (max(pphEquilibriumKcarryCap$PpH_PositiveKcarryCap)-pphEquilibriumKcarryCap$PpH_PositiveKcarryCap[1])/pphEquilibriumKcarryCap$PpH_PositiveKcarryCap[1]*100

######################################################################################################

#Parasites
parasiteMinBNeg <- min(parasiteEquilibriumB$P_NegativeB)
parasiteMaxBNeg <- max(parasiteEquilibriumB$P_NegativeB)

parasiteMinBNull <- min(parasiteEquilibriumB$P_NullB)
parasiteMaxBNull <- max(parasiteEquilibriumB$P_NullB)

parasiteMinBPos <- min(parasiteEquilibriumB$P_PositiveB)
parasiteMaxBPos <- max(parasiteEquilibriumB$P_PositiveB)

parasiteMinDNeg <- min(parasiteEquilibriumD$P_NegativeD)
parasiteMaxDNeg <- max(parasiteEquilibriumD$P_NegativeD)

parasiteMinDNull <- min(parasiteEquilibriumD$P_NullD)
parasiteMaxDNull <- max(parasiteEquilibriumD$P_NullD)

parasiteMinDPos <- min(parasiteEquilibriumD$P_PositiveD)
parasiteMaxDPos <- max(parasiteEquilibriumD$P_PositiveD)

parasiteMinKcarryCapNeg <- min(parasiteEquilibriumKcarryCap$P_NegativeKcarryCap)
parasiteMaxKcarryCapNeg <- max(parasiteEquilibriumKcarryCap$P_NegativeKcarryCap)

parasiteMinKcarryCapNull <- min(parasiteEquilibriumKcarryCap$P_NullKcarryCap)
parasiteMaxKcarryCapNull <- max(parasiteEquilibriumKcarryCap$P_NullKcarryCap)

parasiteMinKcarryCapPos <- min(parasiteEquilibriumKcarryCap$P_PositiveKcarryCap)
parasiteMaxKcarryCapPos <- max(parasiteEquilibriumKcarryCap$P_PositiveKcarryCap)
```

```{r - DETER + Berding MONTHLY - Starting Information - xstart, seasons, time, and resource}
#Setting resource availability
foragingResource <- 3 #try various sizes, 1.5, 2, 2.5, 3
resource <- seq(foragingResource, 10, by=0.1)

xstart <- c(H=69, P=1)
monthsBreeding <- (12*5) #One year is 12 months
time <- seq(1,monthsBreeding,by=1)

#Parameter Values 
b0 <- 0.5980              #monthly rate = 0.5980 
d0 <- 1/5                 #monthly rate = 1/5
alpha0 <- 7.94*10^(-3)    #monthly rate = 7.94*10^(-3) calculated from avg_daily_rate*365/12 [FROM BERDING]
beta0 <- 5.2*10^(-8)      #monthly rate = 5.2*10^(-8)
KcarryCap0 <- 70          #value = 70 per Hectare (100x100m grid)
lambda0 <- 90000          #monthly rate = 90000
gamma0 <- 1/3             #monthly rate = 1/3
mu0 <- 0.375              #monthly rate = 0.375
k0 <- 1                   #value = 1

#Varying the parameters
br = b0*resource
dr = d0/resource
alphar = alpha0/resource
KcarryCapr = KcarryCap0*resource
lambdar = lambda0*resource
gammar = gamma0 #not effected
murPositive = mu0*resource
murNegative = mu0/resource

betarPositive = beta0*foragingResource
betarNegative = beta0/foragingResource
betarNull = beta0+(foragingResource*0)
krPositive = k0*foragingResource
krNegative = k0/foragingResource
krNull = k0+(foragingResource*0)
```

```{r Model -  DETER + Berding MONTHLY - Logistic Growth - Finding resource breakpoints for when each NON-FORAGING parameter undoes the effects of FORAGING parameters on Hosts/Parasites per Host}
#b, d, beta, lambda, mu, gamma, KcarryCap and k from Deter 2008
#Alpha from Berding 1987

#Creating empty vectors
equilibriumH_Baseline <- c()
equilibriumP_Baseline <- c()
tmpBaseline <- c()

equilibriumH_PositiveB <- c()
equilibriumP_PositiveB <- c()
tmpPositiveB <- c()
equilibriumH_NegativeB <- c()
equilibriumP_NegativeB <- c()
tmpNegativeB <- c()

equilibriumH_NegativeD <- c()
equilibriumP_NegativeD <- c()
tmpNegativeD <- c()

equilibriumH_PositiveKcarryCap <- c()
equilibriumP_PositiveKcarryCap <- c()
tmpPositiveKcarryCap <- c()
equilibriumH_NegativeKcarryCap <- c()
equilibriumP_NegativeKcarryCap <- c()
tmpNegativeKcarryCap <- c()

equilibriumH_NegativeAlpha <- c()
equilibriumP_NegativeAlpha <- c()
tmpNegativeAlpha <- c()

equilibriumH_PositiveMuPositive <- c()
equilibriumP_PositiveMuPositive <- c()
tmpPositiveMuPositive <- c()

equilibriumH_NegativeLambda <- c()
equilibriumP_NegativeLambda <- c()
tmpNegativeLambda <- c()

equilibriumH_NegativeMuNegative <- c()
equilibriumP_NegativeMuNegative <- c()
tmpNegativeMuNegative <- c()

#Creating "Finder" variables
hostFirstB <- TRUE
pphFirstB <- TRUE
hostFirstD <- TRUE
pphFirstD <- TRUE
hostFirstKcarryCap <- TRUE
pphFirstKcarryCap <- TRUE
hostFirstAlpha <- TRUE
pphFirstAlpha <- TRUE
hostFirstMuPositive <- TRUE
pphFirstMuPositive <- TRUE
hostFirstLambda <- TRUE
pphFirstLambda <- TRUE
hostFirstMuNegative <- TRUE
pphFirstMuNegative <- TRUE

#Creating Breakpoint Vectors
hostResourceBreakPointForB <- c()
pphResourceBreakPointForB <- c()
hostResourceBreakPointForD <- c()
pphResourceBreakPointForD <- c()
hostResourceBreakPointForKcarryCap <- c()
pphResourceBreakPointForKcarryCap <- c()
hostResourceBreakPointForAlpha <- c()
pphResourceBreakPointForAlpha <- c()
hostResourceBreakPointForMuPositive <- c()
pphResourceBreakPointForMuPositive <- c()
hostResourceBreakPointForLambda <- c()
pphResourceBreakPointForLambda <- c()
hostResourceBreakPointForMuNegative <- c()
pphResourceBreakPointForMuNegative <- c()

#Baseline Scenario for Comparisons
b=b0
d=d0
alpha=alpha0
beta=beta0
lambda=lambda0
gamma=gamma0
mu=mu0
k=k0
KcarryCap = KcarryCap0
#Creating parameters & running model
params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
tmpBaseline <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
equilibriumH_Baseline[length(equilibriumH_Baseline)+1] <- tmpBaseline$H[length(tmpBaseline$H)]
equilibriumP_Baseline[length(equilibriumP_Baseline)+1] <- tmpBaseline$P[length(tmpBaseline$P)]

for (i in 1:length(resource)){ #This will go through the loop for the length of the resource variable
  xstart <- c(H=69, P=1) #Resets the initial parameter values

#[NOTE: This only works when the DIRECTIONALITY of FORAGING and NON-FORAGING PARAMETERS are OPPOSITE]
#Allowing resources to effect non-foraging paramaters (b, d, and KcarryCap) improves the host population [Look at the % Change Effect of baseline]
#Therefore we must select the Resource Effect on Foraging parameters that has the OPPOSITE EFFECT
#There is a POSITIVE effect of resources on Foraging Parameters (beta & k) which is WORSE FOR HOSTS

  #Negative effect of Resources (beta & k) with Positive effect (b)
  b=br[i]
  d=d0
  alpha=alpha0
  beta=betarNegative
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeB <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeB[length(equilibriumH_NegativeB)+1] <- tmpNegativeB$H[length(tmpNegativeB$H)]
  equilibriumP_NegativeB[length(equilibriumP_NegativeB)+1] <- tmpNegativeB$P[length(tmpNegativeB$P)]
  
  #Positive effect of Resources (beta & k & b)
  b=br[i]
  d=d0
  alpha=alpha0
  beta=betarPositive
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveB <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveB[length(equilibriumH_PositiveB)+1] <- tmpPositiveB$H[length(tmpPositiveB$H)]
  equilibriumP_PositiveB[length(equilibriumP_PositiveB)+1] <- tmpPositiveB$P[length(tmpPositiveB$P)]

  #Checking percentage change
  hostOriginalPctChangeForB <- (equilibriumH_PositiveB[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForB <- (equilibriumH_PositiveB[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeB[1]/equilibriumH_NegativeB[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeB[i]/equilibriumH_NegativeB[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForB <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForB <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100

  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstB==TRUE & (sign(hostOriginalPctChangeForB)==-1 & hostCurrentPctChangeForB>0)){
    hostFirstB <- FALSE
    hostResourceBreakPointForB <- resource[i]
  } else if (hostFirstB==TRUE & (sign(hostOriginalPctChangeForB)==1 & hostCurrentPctChangeForB<0)){
    hostFirstB <- FALSE
    hostResourceBreakPointForB <- resource[i]
  } else {
    hostResourceBreakPointForB <- hostResourceBreakPointForB
  }

  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstB==TRUE & (sign(pphOriginalPctChangeForB)==-1 & pphCurrentPctChangeForB>0)){
    pphFirstB <- FALSE
    pphResourceBreakPointForB <- resource[i]
  } else if (pphFirstB==TRUE & (sign(pphOriginalPctChangeForB)==1 & pphCurrentPctChangeForB<0)){
    pphFirstB <- FALSE
    pphResourceBreakPointForB <- resource[i]
  } else {
    pphResourceBreakPointForB <- pphResourceBreakPointForB
  }
      
  #########################################################################################################################################
  
  #Negative effect of Resources (beta & k & d) 
  b=b0
  d=dr[i]
  alpha=alpha0
  beta=betarNegative
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeD <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeD[length(equilibriumH_NegativeD)+1] <- tmpNegativeD$H[length(tmpNegativeD$H)]
  equilibriumP_NegativeD[length(equilibriumP_NegativeD)+1] <- tmpNegativeD$P[length(tmpNegativeD$P)]
  
  #Checking percentage change
  hostOriginalPctChangeForD <- (equilibriumH_NegativeD[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForD <- (equilibriumH_NegativeD[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeD[1]/equilibriumH_NegativeD[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeD[i]/equilibriumH_NegativeD[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForD <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForD <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100

  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstD==TRUE & (sign(hostOriginalPctChangeForD)==-1 & hostCurrentPctChangeForD>0)){
    hostFirstD <- FALSE
    hostResourceBreakPointForD <- resource[i]
  } else if (hostFirstD==TRUE & (sign(hostOriginalPctChangeForD)==1 & hostCurrentPctChangeForD<0)){
    hostFirstD <- FALSE
    hostResourceBreakPointForD <- resource[i]
  } else {
    hostResourceBreakPointForD <- hostResourceBreakPointForD
  }
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstD==TRUE & (sign(pphOriginalPctChangeForD)==-1 & pphCurrentPctChangeForD>0)){
    pphFirstD <- FALSE
    pphResourceBreakPointForD <- resource[i]
  } else if (pphFirstD==TRUE & (sign(pphOriginalPctChangeForD)==1 & pphCurrentPctChangeForD<0)){
    pphFirstD <- FALSE
    pphResourceBreakPointForD <- resource[i]
  } else {
    pphResourceBreakPointForD <- pphResourceBreakPointForD
  }
  
#########################################################################################################################################
  
  #Positive effect of Resources (beta & k & KcarryCap)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krPositive
  KcarryCap = KcarryCapr[i]
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveKcarryCap <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveKcarryCap[length(equilibriumH_PositiveKcarryCap)+1] <- tmpPositiveKcarryCap$H[length(tmpPositiveKcarryCap$H)]
  equilibriumP_PositiveKcarryCap[length(equilibriumP_PositiveKcarryCap)+1] <- tmpPositiveKcarryCap$P[length(tmpPositiveKcarryCap$P)]

  #Negative effect of Resources (beta & k) with Positive effect (KcarryCap) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative
  KcarryCap = KcarryCapr[i]
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeKcarryCap <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeKcarryCap[length(equilibriumH_NegativeKcarryCap)+1] <- tmpNegativeKcarryCap$H[length(tmpNegativeKcarryCap$H)]
  equilibriumP_NegativeKcarryCap[length(equilibriumP_NegativeKcarryCap)+1] <- tmpNegativeKcarryCap$P[length(tmpNegativeKcarryCap$P)]
  
  #Checking percentage change
  hostOriginalPctChangeForKcarryCap <- (equilibriumH_PositiveKcarryCap[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForKcarryCap <- (equilibriumH_PositiveKcarryCap[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeKcarryCap[1]/equilibriumH_NegativeKcarryCap[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeKcarryCap[i]/equilibriumH_NegativeKcarryCap[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForKcarryCap <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForKcarryCap <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100

  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstKcarryCap==TRUE & (sign(hostOriginalPctChangeForKcarryCap)==-1 & hostCurrentPctChangeForKcarryCap>0)){
    hostFirstKcarryCap <- FALSE
    hostResourceBreakPointForKcarryCap <- resource[i]
  } else if (hostFirstKcarryCap==TRUE & (sign(hostOriginalPctChangeForKcarryCap)==1 & hostCurrentPctChangeForKcarryCap<0)){
    hostFirstKcarryCap <- FALSE
    hostResourceBreakPointForKcarryCap <- resource[i]
  } else {
    hostResourceBreakPointForKcarryCap <- hostResourceBreakPointForKcarryCap
  }

  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstKcarryCap==TRUE & (sign(pphOriginalPctChangeForKcarryCap)==-1 & pphCurrentPctChangeForKcarryCap>0)){
    pphFirstKcarryCap <- FALSE
    pphResourceBreakPointForKcarryCap <- resource[i]
  } else if (pphFirstKcarryCap==TRUE & (sign(pphOriginalPctChangeForKcarryCap)==1 & pphCurrentPctChangeForKcarryCap<0)){
    pphFirstKcarryCap <- FALSE
    pphResourceBreakPointForKcarryCap <- resource[i]
  } else {
    pphResourceBreakPointForKcarryCap <- pphResourceBreakPointForKcarryCap
  }

########################################################################################################################################
  
  #Negative effect of Resources (beta, k, & alpha)
  b=b0
  d=d0
  alpha=alphar[i]
  beta=betarNegative
  lambda=lambda0
  gamma=gamma0
  mu=mu0
  k=krNegative
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeAlpha <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeAlpha[length(equilibriumH_NegativeAlpha)+1] <- tmpNegativeAlpha$H[length(tmpNegativeAlpha$H)]
  equilibriumP_NegativeAlpha[length(equilibriumP_NegativeAlpha)+1] <- tmpNegativeAlpha$P[length(tmpNegativeAlpha$P)]

  #Checking percentage change
  hostOriginalPctChangeForAlpha <- (equilibriumH_NegativeAlpha[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForAlpha <- (equilibriumH_NegativeAlpha[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeAlpha[1]/equilibriumH_NegativeAlpha[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeAlpha[i]/equilibriumH_NegativeAlpha[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForAlpha <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForAlpha <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstAlpha==TRUE & (sign(hostOriginalPctChangeForAlpha)==-1 & hostCurrentPctChangeForAlpha>0)){
    hostFirstAlpha <- FALSE
    hostResourceBreakPointForAlpha <- resource[i]
  } else if (hostFirstAlpha==TRUE & (sign(hostOriginalPctChangeForAlpha)==1 & hostCurrentPctChangeForAlpha<0)){
    hostFirstAlpha <- FALSE
    hostResourceBreakPointForAlpha <- resource[i]
  } else {
    hostResourceBreakPointForAlpha <- hostResourceBreakPointForAlpha
  } 
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstAlpha==TRUE & (sign(pphOriginalPctChangeForAlpha)==-1 & pphCurrentPctChangeForAlpha>0)){
    pphFirstAlpha <- FALSE
    pphResourceBreakPointForAlpha <- resource[i]
  } else if (pphFirstAlpha==TRUE & (sign(pphOriginalPctChangeForAlpha)==1 & pphCurrentPctChangeForAlpha<0)){
    pphFirstAlpha <- FALSE
    pphResourceBreakPointForAlpha <- resource[i]
  } else {
    pphResourceBreakPointForAlpha <- pphResourceBreakPointForAlpha
  }
  
########################################################################################################################################

  #Positive effect of Resources (beta, k, & muPositive)
  b=b0
  d=d0
  alpha=alpha0
  beta=betarPositive
  lambda=lambda0
  gamma=gamma0
  mu=murPositive[i]
  k=krPositive
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpPositiveMuPositive <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_PositiveMuPositive[length(equilibriumH_PositiveMuPositive)+1] <- tmpPositiveMuPositive$H[length(tmpPositiveMuPositive$H)]
  equilibriumP_PositiveMuPositive[length(equilibriumP_PositiveMuPositive)+1] <- tmpPositiveMuPositive$P[length(tmpPositiveMuPositive$P)]
  
  #Checking percentage change
  hostOriginalPctChangeForMuPositive <- (equilibriumH_PositiveMuPositive[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForMuPositive <- (equilibriumH_PositiveMuPositive[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_PositiveMuPositive[1]/equilibriumH_PositiveMuPositive[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_PositiveMuPositive[i]/equilibriumH_PositiveMuPositive[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForMuPositive <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForMuPositive <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstMuPositive==TRUE & (sign(hostOriginalPctChangeForMuPositive)==-1 & hostCurrentPctChangeForMuPositive>0)){
    hostFirstMuPositive <- FALSE
    hostResourceBreakPointForMuPositive <- resource[i]
  } else if (hostFirstMuPositive==TRUE & (sign(hostOriginalPctChangeForMuPositive)==1 & hostCurrentPctChangeForMuPositive<0)){
    hostFirstMuPositive <- FALSE
    hostResourceBreakPointForMuPositive <- resource[i]
  } else {
    hostResourceBreakPointForMuPositive <- hostResourceBreakPointForMuPositive
  } 
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstMuPositive==TRUE & (sign(pphOriginalPctChangeForMuPositive)==-1 & pphCurrentPctChangeForMuPositive>0)){
    pphFirstMuPositive <- FALSE
    pphResourceBreakPointForMuPositive <- resource[i]
  } else if (pphFirstMuPositive==TRUE & (sign(pphOriginalPctChangeForMuPositive)==1 & pphCurrentPctChangeForMuPositive<0)){
    pphFirstMuPositive <- FALSE
    pphResourceBreakPointForMuPositive <- resource[i]
  } else {
    pphResourceBreakPointForMuPositive <- pphResourceBreakPointForMuPositive
  }
  
########################################################################################################################################
  
  #Negative effect of Resources (beta & k & lambda) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative
  lambda=lambdar[i]
  gamma=gamma0
  mu=mu0
  k=krNegative
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeLambda <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeLambda[length(equilibriumH_NegativeLambda)+1] <- tmpNegativeLambda$H[length(tmpNegativeLambda$H)]
  equilibriumP_NegativeLambda[length(equilibriumP_NegativeLambda)+1] <- tmpNegativeLambda$P[length(tmpNegativeLambda$P)]
  
  #Checking percentage change
  hostOriginalPctChangeForLambda <- (equilibriumH_NegativeLambda[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForLambda <- (equilibriumH_NegativeLambda[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeLambda[1]/equilibriumH_NegativeLambda[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeLambda[i]/equilibriumH_NegativeLambda[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForLambda <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForLambda <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstLambda==TRUE & (sign(hostOriginalPctChangeForLambda)==-1 & hostCurrentPctChangeForLambda>0)){
    hostFirstLambda <- FALSE
    hostResourceBreakPointForLambda <- resource[i]
  } else if (hostFirstLambda==TRUE & (sign(hostOriginalPctChangeForLambda)==1 & hostCurrentPctChangeForLambda<0)){
    hostFirstLambda <- FALSE
    hostResourceBreakPointForLambda <- resource[i]
  } else {
    hostResourceBreakPointForLambda <- hostResourceBreakPointForLambda
  } 
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstLambda==TRUE & (sign(pphOriginalPctChangeForLambda)==-1 & pphCurrentPctChangeForLambda>0)){
    pphFirstLambda <- FALSE
    pphResourceBreakPointForLambda <- resource[i]
  } else if (pphFirstLambda==TRUE & (sign(pphOriginalPctChangeForLambda)==1 & pphCurrentPctChangeForLambda<0)){
    pphFirstLambda <- FALSE
    pphResourceBreakPointForLambda <- resource[i]
  } else {
    pphResourceBreakPointForLambda<- pphResourceBreakPointForLambda
  }
  
########################################################################################################################################
  
  #Negative effect of Resources (beta & k & muNegative) 
  b=b0
  d=d0
  alpha=alpha0
  beta=betarNegative
  lambda=lambda0
  gamma=gamma0
  mu=murNegative[i]
  k=krNegative
  KcarryCap = KcarryCap0
  #Creating parameters & running model
  params <- c(b, d, alpha, beta, lambda, gamma, mu, k, KcarryCap)
  tmpNegativeMuNegative <- as.data.frame(ode(xstart, time, macroParasiteLogistic, params))
  equilibriumH_NegativeMuNegative[length(equilibriumH_NegativeMuNegative)+1] <- tmpNegativeMuNegative$H[length(tmpNegativeMuNegative$H)]
  equilibriumP_NegativeMuNegative[length(equilibriumP_NegativeMuNegative)+1] <- tmpNegativeMuNegative$P[length(tmpNegativeMuNegative$P)]
  
  #Checking percentage change
  hostOriginalPctChangeForMuNegative <- (equilibriumH_NegativeMuNegative[1]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  hostCurrentPctChangeForMuNegative <- (equilibriumH_NegativeMuNegative[i]-equilibriumH_Baseline[1])/equilibriumH_Baseline[1]*100
  
  pphOriginalPctChangeTerm1 <- equilibriumP_NegativeMuNegative[1]/equilibriumH_NegativeMuNegative[1]
  pphOriginalPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphOriginalPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphCurrentPctChangeTerm1 <- equilibriumP_NegativeMuNegative[i]/equilibriumH_NegativeMuNegative[i]
  pphCurrentPctChangeTerm2 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  pphCurrentPctChangeTerm3 <- equilibriumP_Baseline[1]/equilibriumH_Baseline[1]
  
  pphOriginalPctChangeForMuNegative <- (pphOriginalPctChangeTerm1-pphOriginalPctChangeTerm2)/pphOriginalPctChangeTerm3*100
  pphCurrentPctChangeForMuNegative <- (pphCurrentPctChangeTerm1-pphCurrentPctChangeTerm2)/pphCurrentPctChangeTerm3*100
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (hostFirstMuNegative==TRUE & (sign(hostOriginalPctChangeForMuNegative)== -1 & hostCurrentPctChangeForMuNegative>0)){
    hostFirstMuNegative <- FALSE
    hostResourceBreakPointForMuNegative <- resource[i]
  } else if (hostFirstMuNegative==TRUE & (sign(hostOriginalPctChangeForMuNegative)== 1 & hostCurrentPctChangeForMuNegative<0)){
    hostFirstMuNegative <- FALSE
    hostResourceBreakPointForMuNegative <- resource[i]
  } else {
    hostResourceBreakPointForMuNegative <- hostResourceBreakPointForMuNegative
  } 
  
  #If statement to check when the nonforaging parameter is able to "undo or overpower" the foraging parameters effect
  if (pphFirstMuNegative==TRUE & (sign(pphOriginalPctChangeForMuNegative)== -1 & pphCurrentPctChangeForMuNegative>0)){
    pphFirstMuNegative <- FALSE
    pphResourceBreakPointForMuNegative <- resource[i]
  } else if (pphFirstMuNegative==TRUE & (sign(pphOriginalPctChangeForMuNegative)== 1 & pphCurrentPctChangeForMuNegative<0)){
    pphFirstMuNegative <- FALSE
    pphResourceBreakPointForMuNegative <- resource[i]
  } else {
    pphResourceBreakPointForMuNegative <- pphResourceBreakPointForMuNegative
  }
  
}

```

```{r Graphing - STATIC FORAGING = 1.5 - Plot parameter along x-axis, breakpoints along y-axis}
#hostDataALL <- data.frame(Value=c(hostResourceBreakPointForB, hostResourceBreakPointForD, hostResourceBreakPointForKcarryCap, hostResourceBreakPointForAlpha, hostResourceBreakPointForMuPositive,
#                               hostResourceBreakPointForLambda, hostResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

hostData <- data.frame(Value=c(hostResourceBreakPointForB, hostResourceBreakPointForMuPositive, hostResourceBreakPointForLambda),
                       Parameter=c("b", "Mu+", "Lambda"),
                       NNP=c("Positive", "Positive", "Negative")
                       )


#pphDataAll <- data.frame(Value=c(pphResourceBreakPointForB, pphResourceBreakPointForD, pphResourceBreakPointForKcarryCap, pphResourceBreakPointForAlpha, pphResourceBreakPointForMuPositive,
#                               pphResourceBreakPointForLambda, pphResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

pphData <- data.frame(Value=c(pphResourceBreakPointForKcarryCap, pphResourceBreakPointForMuPositive, pphResourceBreakPointForLambda),
                      Parameter=c("Hmax", "Mu+", "Lambda"),
                      NNP=c("Negative", "Positive", "Negative")
                      )

colors <- c("Negative" = "lightcoral", "Positive" = "lightblue")

hostBreakpoints <- ggplot(data=hostData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("b", "Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Host Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Foraging Resource Size 1.5") + 
  theme_bw()

pphBreakpoints <- ggplot(data=pphData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Hmax", "Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Pph Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Non-Foraging Resource Size 1.5-10") + 
  theme_bw()

legendDataframe <- data.frame(X_Value=c(1, 1, 2, 2),
                          Y_Value=c(1, 1, 2, 2),
                          NNP=c("Negative", "Negative", "Positive", "Positive"))


legendPlot <- ggplot(data=legendDataframe) + 
  geom_line(aes(x=X_Value, y=Y_Value, col=NNP)) +
  labs(col="Resource Affect on Infection Parameters") +
  scale_color_manual(values=colors) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  theme_bw()

legendPlot <- cowplot::get_legend(legendPlot)

plot_grid(hostBreakpoints, pphBreakpoints, legendPlot, labels=NULL, ncol=3, nrow=1)

```

```{r Graphing - STATIC FORAGING = 2 - Plot parameter along x-axis, breakpoints along y-axis}
#hostDataALL <- data.frame(Value=c(hostResourceBreakPointForB, hostResourceBreakPointForD, hostResourceBreakPointForKcarryCap, hostResourceBreakPointForAlpha, hostResourceBreakPointForMuPositive,
#                               hostResourceBreakPointForLambda, hostResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

hostData <- data.frame(Value=c(hostResourceBreakPointForMuPositive, hostResourceBreakPointForLambda),
                       Parameter=c("Mu+", "Lambda"),
                       NNP=c("Positive", "Negative")
                       )


#pphDataAll <- data.frame(Value=c(pphResourceBreakPointForB, pphResourceBreakPointForD, pphResourceBreakPointForKcarryCap, pphResourceBreakPointForAlpha, pphResourceBreakPointForMuPositive,
#                               pphResourceBreakPointForLambda, pphResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

pphData <- data.frame(Value=c(pphResourceBreakPointForKcarryCap, pphResourceBreakPointForMuPositive, pphResourceBreakPointForLambda),
                      Parameter=c("Hmax", "Mu+", "Lambda"),
                      NNP=c("Negative", "Positive", "Negative")
                      )

colors <- c("Negative" = "lightcoral", "Positive" = "lightblue")

hostBreakpoints <- ggplot(data=hostData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Host Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Foraging Resource Size 2") + 
  theme_bw()

pphBreakpoints <- ggplot(data=pphData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Hmax", "Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Pph Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Non-Foraging Resource Size 2-10") + 
  theme_bw()

legendDataframe <- data.frame(X_Value=c(1, 1, 2, 2),
                          Y_Value=c(1, 1, 2, 2),
                          NNP=c("Negative", "Negative", "Positive", "Positive"))


legendPlot <- ggplot(data=legendDataframe) + 
  geom_line(aes(x=X_Value, y=Y_Value, col=NNP)) +
  labs(col="Resource Affect on Infection Parameters") +
  scale_color_manual(values=colors) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  theme_bw()

legendPlot <- cowplot::get_legend(legendPlot)

plot_grid(hostBreakpoints, pphBreakpoints, legendPlot, labels=NULL, ncol=3, nrow=1)

```

```{r Graphing - STATIC FORAGING = 2.5 - Plot parameter along x-axis, breakpoints along y-axis}
#hostDataALL <- data.frame(Value=c(hostResourceBreakPointForB, hostResourceBreakPointForD, hostResourceBreakPointForKcarryCap, hostResourceBreakPointForAlpha, hostResourceBreakPointForMuPositive,
#                               hostResourceBreakPointForLambda, hostResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

hostData <- data.frame(Value=c(hostResourceBreakPointForMuPositive, hostResourceBreakPointForLambda),
                       Parameter=c("Mu+", "Lambda"),
                       NNP=c("Positive", "Negative")
                       )


#pphDataAll <- data.frame(Value=c(pphResourceBreakPointForB, pphResourceBreakPointForD, pphResourceBreakPointForKcarryCap, pphResourceBreakPointForAlpha, pphResourceBreakPointForMuPositive,
#                               pphResourceBreakPointForLambda, pphResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

pphData <- data.frame(Value=c(pphResourceBreakPointForKcarryCap, pphResourceBreakPointForMuPositive, pphResourceBreakPointForLambda),
                      Parameter=c("Hmax", "Mu+", "Lambda"),
                      NNP=c("Negative", "Positive", "Negative")
                      )

colors <- c("Negative" = "lightcoral", "Positive" = "lightblue")

hostBreakpoints <- ggplot(data=hostData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Host Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Foraging Resource Size 2.5") + 
  theme_bw()

pphBreakpoints <- ggplot(data=pphData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Hmax", "Mu+", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Pph Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Non-Foraging Resource Size 2.5-10") + 
  theme_bw()

legendDataframe <- data.frame(X_Value=c(1, 1, 2, 2),
                          Y_Value=c(1, 1, 2, 2),
                          NNP=c("Negative", "Negative", "Positive", "Positive"))


legendPlot <- ggplot(data=legendDataframe) + 
  geom_line(aes(x=X_Value, y=Y_Value, col=NNP)) +
  labs(col="Resource Affect on Infection Parameters") +
  scale_color_manual(values=colors) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  theme_bw()

legendPlot <- cowplot::get_legend(legendPlot)

plot_grid(hostBreakpoints, pphBreakpoints, legendPlot, labels=NULL, ncol=3, nrow=1)

```

```{r Graphing - STATIC FORAGING = 3 - Plot parameter along x-axis, breakpoints along y-axis}
#hostDataALL <- data.frame(Value=c(hostResourceBreakPointForB, hostResourceBreakPointForD, hostResourceBreakPointForKcarryCap, hostResourceBreakPointForAlpha, hostResourceBreakPointForMuPositive,
#                               hostResourceBreakPointForLambda, hostResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

hostData <- data.frame(Value=c(hostResourceBreakPointForLambda),
                       Parameter=c("Lambda"),
                       NNP=c("Negative")
                       )


#pphDataAll <- data.frame(Value=c(pphResourceBreakPointForB, pphResourceBreakPointForD, pphResourceBreakPointForKcarryCap, pphResourceBreakPointForAlpha, pphResourceBreakPointForMuPositive,
#                               pphResourceBreakPointForLambda, pphResourceBreakPointForMuNegative),
#                       Parameter=c("b", "d", "Hmax", "Alpha", "Mu+", "Lambda", "Mu-")
#                       )

pphData <- data.frame(Value=c(pphResourceBreakPointForKcarryCap, pphResourceBreakPointForLambda),
                      Parameter=c("Hmax", "Lambda"),
                      NNP=c("Negative", "Negative")
                      )

colors <- c("Negative" = "lightcoral", "Positive" = "lightblue")

hostBreakpoints <- ggplot(data=hostData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Host Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Foraging Resource Size 3") + 
  theme_bw()

pphBreakpoints <- ggplot(data=pphData, aes(x=Parameter, y=Value, fill=NNP)) +
  scale_x_discrete(limits=c("Hmax", "Lambda")) +
  geom_bar(stat="identity", position=position_dodge(), show.legend = FALSE) +
  labs(x = expression(bold("Non-Foraging Parameters")),
       y = expression(bold("Pph Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  scale_color_manual(values=colors) +
  ggtitle("Non-Foraging Resource Size 3-10") + 
  theme_bw()

legendDataframe <- data.frame(X_Value=c(1, 1, 2, 2),
                          Y_Value=c(1, 1, 2, 2),
                          NNP=c("Negative", "Negative", "Positive", "Positive"))


legendPlot <- ggplot(data=legendDataframe) + 
  geom_line(aes(x=X_Value, y=Y_Value, col=NNP)) +
  labs(col="Resource Affect on Infection Parameters") +
  scale_color_manual(values=colors) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  theme_bw()

legendPlot <- cowplot::get_legend(legendPlot)

plot_grid(hostBreakpoints, pphBreakpoints, legendPlot, labels=NULL, ncol=3, nrow=1)

```

################################################################################################################### 

#Old Linear regression stuff

```{r - OLD - Attempts to find LMEndPoints for graphing the symbol larger (these didn't work)}
"
hostBirthLMEndPoint = unname((hostBirthLM$coefficients[1] + hostBirthLM$coefficients[2]*max(hostForagingResourceForB))) 
hostDeathLMEndPoint = unname((hostDeathLM$coefficients[1] + hostDeathLM$coefficients[2]*max(hostForagingResourceForD))) 
hostCarryingCapacityLMEndPoint = unname((hostCarryingCapacityLM$coefficients[1] + hostCarryingCapacityLM$coefficients[2]*max(hostForagingResourceForKcarryCap))) 
#hostParasiteVirulenceLMEndPoint = unname((hostParasiteVirulenceLM$coefficients[1] + hostParasiteVirulenceLM$coefficients[2]*max(hostForagingResourceForAlpha))) #Doesn't work only 1 point
hostMuPositiveLMEndPoint = unname((hostMuPositiveLM$coefficients[1] + hostMuPositiveLM$coefficients[2]*max(hostForagingResourceForMuPositive)))
hostLambdaLMEndPoint = unname((hostLambdaLM$coefficients[1] + hostLambdaLM$coefficients[2]*max(hostForagingResourceForLambda)))
hostMuNegativeLMEndPoint = unname((hostMuNegativeLM$coefficients[1] + hostMuNegativeLM$coefficients[2]*max(hostForagingResourceForMuNegative)))

pphBirthLMEndPoint = unname((pphBirthLM$coefficients[1] + pphBirthLM$coefficients[2]*max(pphForagingResourceForB))) 
pphDeathLMEndPoint = unname((pphDeathLM$coefficients[1] + pphDeathLM$coefficients[2]*max(pphForagingResourceForD))) 
pphCarryingCapacityLMEndPoint = unname((pphCarryingCapacityLM$coefficients[1] + pphCarryingCapacityLM$coefficients[2]*max(pphForagingResourceForKcarryCap))) 
pphParasiteVirulenceLMEndPoint = unname((pphParasiteVirulenceLM$coefficients[1] + pphParasiteVirulenceLM$coefficients[2]*max(pphForagingResourceForAlpha)))
pphMuPositiveLMEndPoint = unname((pphMuPositiveLM$coefficients[1] + pphMuPositiveLM$coefficients[2]*max(pphForagingResourceForMuPositive)))
pphLambdaLMEndPoint = unname((pphLambdaLM$coefficients[1] + pphLambdaLM$coefficients[2]*max(pphForagingResourceForLambda)))
pphMuNegativeLMEndPoint = unname((pphMuNegativeLM$coefficients[1] + pphMuNegativeLM$coefficients[2]*max(pphForagingResourceForMuNegative)))

hostBirthLMEndPointPair = max(hostForagingResourceForB)
hostDeathLMEndPointPair = max(hostForagingResourceForD) 
hostCarryingCapacityLMEndPointPair = max(hostForagingResourceForKcarryCap)
#hostParasiteVirulenceLMEndPointPair = max(hostForagingResourceForAlpha) #Doesn't work only 1 point
hostMuPositiveLMEndPointPair = max(hostForagingResourceForMuPositive)
hostLambdaLMEndPointPair = max(hostForagingResourceForLambda)
hostMuNegativeLMEndPointPair = max(hostForagingResourceForMuNegative)

pphBirthLMEndPointPair = max(pphForagingResourceForB)
pphDeathLMEndPointPair = max(pphForagingResourceForD) 
pphCarryingCapacityLMEndPointPair = max(pphForagingResourceForKcarryCap)
pphParasiteVirulenceLMEndPointPair = max(pphForagingResourceForAlpha) #Doesn't work only 1 point
pphMuPositiveLMEndPointPair = max(pphForagingResourceForMuPositive)
pphLambdaLMEndPointPair = max(pphForagingResourceForLambda)
pphMuNegativeLMEndPointPair = max(pphForagingResourceForMuNegative)

############################################################################################################

#Saving the ENDING POINT of line of best fit so that we can graph the symbols larger later
hostBirthLMEndPoint <- tail(hostBirthLMPoints, 1) #grabbing the last value (our ending point)
hostDeathLMEndPoint <- tail(hostDeathLMPoints, 1)
hostCarryingCapacityLMEndPoint <- tail(hostCarryingCapacityLMPoints, 1)
#hostParasiteVirulenceLMEndPoint <- tail(hostParasiteVirulenceLMPoints, 1) #doesn't work because only 1 point
hostMuPositiveLMEndPoint <- tail(hostMuPositiveLMPoints, 1)
hostLambdaLMEndPoint <- tail(hostLambdaLMPoints, 1)
hostMuNegativeLMEndPoint <- tail(hostMuNegativeLMPoints, 1)

hostBirthLMEndPointPair <- tail(hostBirthLMPointsPair, 1)
hostDeathLMEndPointPair <- tail(hostDeathLMPointsPair, 1)
hostCarryingCapacityLMEndPointPair <- tail(hostCarryingCapacityLMPointsPair, 1)
#hostParasiteVirulenceLMEndPointPair <- tail(hostParasiteVirulenceLMPointsPair, 1) #doesn't work because only 1 point
hostMuPositiveLMEndPointPair <- tail(hostMuPositiveLMPointsPair, 1)
hostLambdaLMEndPointPair <- tail(hostLambdaLMPointsPair, 1)
hostMuNegativeLMEndPointPair <- tail(hostMuNegativeLMPointsPair, 1)

pphBirthLMEndPoint <- tail(pphBirthLMPoints, 1)
pphDeathLMEndPoint <- tail(pphDeathLMPoints, 1)
pphCarryingCapacityLMEndPoint <- tail(pphCarryingCapacityLMPoints, 1)
pphParasiteVirulenceLMEndPoint <- tail(pphParasiteVirulenceLMPoints, 1)
pphMuPositiveLMEndPoint <- tail(pphMuPositiveLMPoints, 1)
pphLambdaLMEndPoint <- tail(pphLambdaLMPoints, 1)
pphMuNegativeLMEndPoint <- tail(pphMuNegativeLMPoints, 1)

pphBirthLMEndPointPair <- tail(pphBirthLMPointsPair, 1)
pphDeathLMEndPointPair <- tail(pphDeathLMPointsPair, 1)
pphCarryingCapacityLMEndPointPair <- tail(pphCarryingCapacityLMPointsPair, 1)
pphParasiteVirulenceLMEndPointPair <- tail(pphParasiteVirulenceLMPointsPair, 1)
pphMuPositiveLMEndPointPair <- tail(pphMuPositiveLMPointsPair, 1)
pphLambdaLMEndPointPair <- tail(pphLambdaLMPointsPair, 1)
pphMuNegativeLMEndPointPair <- tail(pphMuNegativeLMPointsPair, 1)
"

```

################################################################################################################### 

#Old graph that plots points along the lines. JUst a bit too messy.

```{r - OLD - Graphing - Plot foragingResource along x-axis, breakpoints along y-axis, colored/marked by parameter and NNP type}
hostBreakpoints <- ggplot(data=hostDataAll, aes(x=foragingResourceLevel, y=resourceBreakPoints, group=nonForagingParameter)) +
  geom_line(aes(color=NNP), size=1.2) +        
  geom_point(aes(shape=nonForagingParameter), size=1.2) + #, show.legend=FALSE
  scale_shape_manual(values=seq(1, length(unique(hostDataAll$nonForagingParameter)))) +
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +            #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                            #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")),
       y = expression(bold("Host Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points
  #ggtitle() + 
  theme_bw()

pphBreakpoints <- ggplot(data=pphDataAll, aes(x=foragingResourceLevel, y=resourceBreakPoints, group=nonForagingParameter)) +
  geom_line(aes(color=NNP), size=1.2) +        
  geom_point(aes(shape=nonForagingParameter), size=1.2) +  #, position=position_dodge(width=0.05)
  scale_shape_manual(values=seq(1, length(unique(pphDataAll$nonForagingParameter)))) +
  geom_abline(slope=1, intercept=0, color="black", linetype="dashed", size=1.2) +
  xlim(min(foragingResource)-0.05, max(foragingResource)+0.05) +                      #xlim(min(foragingResource)-0.2, max(foragingResource)+0.2)
  ylim(min(resource)-0.05, max(resource)+0.05) +                                      #ylim(min(resource)-0.2, max(resource)+0.2)
  labs(x = expression(bold("Foraging Resource Effect")),
       y = expression(bold("Pph Resource Breakpoint")),
       fill="Effect on Foraging Parameters") +
  guides(color = guide_legend(override.aes=(list(type=0)))) + #removes the shape from NNP in legend
  guides(color = guide_legend(title="Effect of Resources on Foraging Parameters")) + #Changes title of legend for line color
  guides(shape = guide_legend(title="Non-Foraging Parameters")) + #Changes title of legend for shape of points  #ggtitle() + 
  theme_bw()


#hostLegendPlot <- ggplot(data=hostDataAll, aes(x=foragingResourceLevel, y=resourceBreakPoints, #group=nonForagingParameter)) +
#  geom_line(aes(color=NNP), size=1.2, show.legend=TRUE) +
#  geom_point(aes(shape=nonForagingParameter), size=1.2, show.legend=TRUE) +
#  scale_shape_manual(values=seq(1, length(unique(hostDataAll$nonForagingParameter)))) +
#  xlim(min(foragingResource), max(foragingResource)) +   
#  ylim(min(resource), max(resource)) + 
#  labs(x = expression(bold("Foraging Resource Effect")),
#       y = expression(bold("Host Resource Breakpoint")),
#       fill="Effect on Foraging Parameters") +
#  #ggtitle() + 
#  theme_bw()

#pphLegendPlot <- ggplot(data=pphDataAll, aes(x=foragingResourceLevel, y=resourceBreakPoints, #group=nonForagingParameter)) +
#  geom_line(aes(color=NNP), size=1.2, show.legend=TRUE) +            
#  geom_point(aes(shape=nonForagingParameter), size=1.2, show.legend=TRUE, ) + #, position=position_dodge(width=0.2)
#  scale_shape_manual(values=seq(1, length(unique(pphDataAll$nonForagingParameter)))) +
#  xlim(min(foragingResource), max(foragingResource)) +                    #xlim(min(foragingResource)-0.2, #max(foragingResource)+0.2)
#  ylim(min(resource), max(resource)) +                                    #ylim(min(resource)-0.2, #max(resource)+0.2)
#  labs(x = expression(bold("Foraging Resource Effect")),
#       y = expression(bold("Pph Resource Breakpoint")),
#       fill="Effect on Foraging Parameters") +
#  #ggtitle() + 
#  theme_bw()

#hostLegendPlot <- cowplot::get_legend(hostLegendPlot)
#pphLegendPlot <- cowplot::get_legend(pphLegendPlot)

#plot_grid(hostBreakpoints, hostLegendPlot, pphBreakpoints, pphLegendPlot, ncol=2, nrow=2)


plot_grid(hostBreakpoints, pphBreakpoints, ncol=1, nrow=2)

```

```{r - abline works but it's ugly and ruins the legend}
  geom_abline(slope=hostBirthLM$coefficients[2], intercept=hostBirthLM$coefficients[1], size=1.1, color="lightblue") +
  geom_abline(slope=hostDeathLM$coefficients[2], intercept=hostDeathLM$coefficients[1], size=1.1, color="lightcoral") +
  geom_abline(slope=hostCarryingCapacityLM$coefficients[2], intercept=hostCarryingCapacityLM$coefficients[1], size=1.1, color="lightblue") +
  geom_abline(slope=hostMuPositiveLM$coefficients[2], intercept=hostMuPositiveLM$coefficients[1], size=1.1, color="lightblue") +
  geom_abline(slope=hostLambdaLM$coefficients[2], intercept=hostLambdaLM$coefficients[1], size=1.1, color="lightcoral") +
  geom_abline(slope=hostMuNegativeLM$coefficients[2], intercept=hostMuNegativeLM$coefficients[1], size=1.1, color="lightcoral") +
```
